### ISSUE TITLE
Database not properly cleaned

### ISSUE THREAD

**Issue by conradwt** [DatabaseCleaner/database_cleaner#123]
The database, MySQL, isn't being properly cleaned using the RSpec recipe below:

```
RSpec.configure do |config|

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

end
```

Setup:

```
OS:                             Mac OS 10.7.4

Ruby:                         1.9.2p323

Rails:                          3.2.6

DatabaseCleaner:   0.8.0

mysql2:                      0.3.11

MySQL:                     5.1.62

rspec:                         2.10.0

rspec-rails:                2.10.1
```

Lastly, this isn't so much of an issue with the unit tests but causes issues with the controller and acceptance tests.

**Comment by alecslupu** [comment]
I have encountered the problem myself in a Rails 3.2 + Rspec 3 environment. Changing my rails_helper.rb to : 

`  config.use_transactional_fixtures = false `

solved my problems. 
A

**Comment by DemitryT** [comment]
I was running into a similar issue, but eventually got it to work with the `truncation` strategy. My issue ended up being that I was using ActiveRecord to create some of the objects I was working with in my tests when I should have been using factories I had setup with FactoryGirl. Hope that helps someone.

**Comment by ka8725** [comment]
Just in case. I had a similar case, for some reason some user records were not cleaned from DB. My analysis showed that those records that assigned to `Thread.current` are not cleaned automatically by DatabaseCleaner.

So I come up with the fix:

```ruby
  config.after(:each) do
    # Thread.current[:current_user] is set in some tests
    # it should be cleaned before database cleaner runs, otherwise it won't be dropped from DB.
    Thread.current[:current_user] = nil
    DatabaseCleaner.clean
    puts User.count # this output along with running "rspec --format d" can show the places causing issues in the app
  end
```
