### ISSUE TITLE
Having trouble with database_cleaner on jenkins/hudson ci server

### ISSUE THREAD

**Issue by tabfugnic** [DatabaseCleaner/database_cleaner#176]
So I'm setting up a CI Server using hudson 3.0.  After getting it all up and running I have a few tests that fail.  Check to see what's going on and I finally figure out that the data that I'm throwing into my database isn't getting cleaned out properly. 

I've run my test suite on a bunch of different machines and they all seem to work, but when I run it manually on the CI server it also breaks and doesn't do the proper cleanup.  The logs don't look all that strange on the server it looks as though it's doing everything correctly, but still nothing is lost.

Here's my  spec_helper.rb

```ruby
config.before :all do
  init_haml_helpers
end
config.use_transactional_fixtures = false

config.before(:suite) do
  Headless.new(:destroy_on_exit => false).start
  DatabaseCleaner.strategy = :transaction
  DatabaseCleaner.clean_with :truncation
end

config.before(:each) do
  Capybara.reset_sessions!
  if example.metadata[:js]
    Capybara.current_driver = :selenium
    DatabaseCleaner.strategy = :truncation
  else
    DatabaseCleaner.start
  end
end
config.after(:each) do
  Capybara.use_default_driver if example.metadata[:js]
  DatabaseCleaner.clean
  DatabaseCleaner.strategy = :transaction if example.metadata[:js]
end
```

Relevant Software being used
Gems:
- rails 3.0.19
- factory_girl 4.0
- database_cleaner 0.6.7
- spork - only on my own machine
- rspec 2.12
- capybara 2.0.2

Software:
- MySql 5.1
- Ubuntu 11.04
- Ruby 1.9.3 via RVM

**Comment by etagwerker** [comment]
@tabfugnic Is this still an issue? The only thing that I'd advise is to use `append_after` instead of `after` - See: https://github.com/DatabaseCleaner/database_cleaner#rspec-with-capybara-example

**Comment by tabfugnic** [comment]
@etagwerker I'm uncertain whether or not this is still an issue. I think this can safely be closed.
