### ISSUE TITLE
Check if the strategy is the same before creating a new strategy object in 'strategy='

### ISSUE THREAD

**Issue by andreypronin** [DatabaseCleaner/database_cleaner#183]
Note the difference between the DatabaseCleaner usage code in these two places and the rationale for that difference:
http://devblog.avdi.org/2012/08/31/configuring-database_cleaner-with-rails-rspec-capybara-and-selenium/
vs
https://gist.github.com/moonfly/4950750.

For example, setting "DatabaseCleaner.strategy = :transaction" (as in the 1st post) before each spec leads to DatabaseCleaner::ActiveRecord::Transaction.new (assuming AR ORM case, of course) being called for each connection (extra time + extra work for GC).
Obviously, this is not the intended use of 'strategy=' call, but the intentions (i.e. "gain all performance benefits we can for tests") are well aligned with the intentions of the DatabaseCleaner itself.

**Comment by etagwerker** [comment]
@andreypronin Sorry for the delay. The gist is no longer available, so I'm missing information. If this is still an issue, please re-open it in this project: https://github.com/DatabaseCleaner/database_cleaner-active_record
