### ISSUE TITLE
Should use TRUNCATE ... CASCADE or similar on Postgres

### ISSUE THREAD

**Issue by Empact** [DatabaseCleaner/database_cleaner#2]
In the presence of constraints, a regular truncate will fail on postgres.  DatabaseCleaner should either CASCADE the TRUNCATE or defer enforcement of the constraints.

**Comment by foton** [comment]
Is there way to turn off `cascade` for `DatabaseCleaner.clean_with(strategy, except: KEEP_TABLES)` ? It deletes record (binded) in tables listed in KEEP_TABLES.
