### ISSUE TITLE
can not use the transaction strategy when using multiple DBs (with AR)...

### ISSUE THREAD

**Issue by bmabey** [DatabaseCleaner/database_cleaner#22]
This fails the tests, at least with ActiveRecord.  Still need to manually test this to verify it isn't a testing bug.  Either way, this needs to be fixed.

**Comment by toomanyjoes** [comment]
I am having a problem in my app and this issue seems like it could be related. I cannot tell if this was ever merged and published. Is this fix in the current version of the gem?
