### ISSUE TITLE
Strange rails4 + establish_connection issue

### ISSUE THREAD

**Issue by hannesfostie** [DatabaseCleaner/database_cleaner#245]
Hey

I'm sorry if this is described vaguely, I'm afraid we haven't been able to pinpoint the problem yet.

Situation is as follows:

- We have a legacy database for a number of our models. We connect to this using `establish_connection` in the models and also use `self.table_name_prefix` to change the table name.
- We set up database_cleaner to use different strategies for this database (I honestly forgot why, apparently it was required at one point but I forgot the details):

```
DatabaseCleaner[:active_record, {connection: :mail_database_test}].strategy = :truncation
```

- Upon upgrading to Rails4, I changed all observers to concerns. These just add an after_create, destroy and update callback to a bunch of models, notifying our logging system of changes made.

We noticed a number of tests started to break. Removing the above code (altered strategy) seemed to improve, but that's obviously not ideal. We also noticed that the tests didn't break immediatly, they only broke after we actually went and removed the observers themselves. If the observer class is still there (but empty) the tests work. If we remove the file, they break.

```
19) Api::AccountsController#update should update an account
     Failure/Error: @client = create :client
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Table 'app_secondary_db_test.clients' doesn't exist: SHOW FULL FIELDS FROM `clients`
```

The clients table doesn't exist because this model actually uses the primary database.

We get the feeling this may be a problem with databasecleaner, possibly with the caching of the tables.

Completely out of ideas. Thanks!

**Comment by etagwerker** [comment]
@wendy0402 You could try with this alternative: https://gist.github.com/mgreenly/1109325
