### ISSUE TITLE
Gettinng error as NoMethodError:undefined method 'cleaning'

### ISSUE THREAD

**Issue by kirtithorat** [DatabaseCleaner/database_cleaner#258]
I included database_cleaner gem in my rails app sourced from RubyGems.org. Followed the example given on this git repo and included the following code in spec_helper :

  config.before(:suite) do
   DatabaseCleaner.strategy = :transaction
   DatabaseCleaner.clean_with(:truncation)
  end
  config.around(:each) do |example|
   DatabaseCleaner.cleaning do
    example.run
   end
  end
When i run the rspec i get error as NoMethodError:undefined method 'cleaning' for DatabaseCleaner:Module.

After spending hours I found out that RubyGems.org gem is not up-to date. "Cleaning" example method works perfectly when I include the source of the gem from github repo in my gemfile config.

When will be the RubyGems.org gem updated? Also, it will be good idea to have note on this repo about this new addition. Thanks for the great work! Database_Cleaner is a real gem. Love it. Keep it up.

**Comment by jeffrey008** [comment]
It seems like an old post, but upgrading `database_cleaner` to `1.5.0` solves the problem for me.
