### ISSUE TITLE
Add a way to see which strategy is in use?

### ISSUE THREAD

**Issue by mockdeep** [DatabaseCleaner/database_cleaner#264]
I've been trying to debug my tests and wanted to see which strategy was in use. Turns out I was under the mistaken belief that I was using transaction for everything but the integration specs, and truncation for those. At any rate, in order to debug, I needed to do this:

```ruby
DatabaseCleaner.instance_variable_get(:@cleaners)[[:active_record, {}]].instance_variable_get(:@strategy).class
```

It would be nice to have something like:

```ruby
DatabaseCleaner.strategy
```

**Comment by Zorbash** [comment]
In [v1.3.0](https://github.com/DatabaseCleaner/database_cleaner/tree/v1.3.0) that i'm using, it's possible to do 

```ruby
DatabaseCleaner[:active_record].strategy.class
```
for debugging pursposes.
Which version of database_cleaner are you using? Are you still facing the issue?

**Comment by mockdeep** [comment]
I haven't used this in a while, but it sounds like the issue can be closed now.
