### ISSUE TITLE
Not working with Pg 9.3 / ruby 2.1.2

### ISSUE THREAD

**Issue by muichkine** [DatabaseCleaner/database_cleaner#268]
Hello,
    I've updated my environnment with postgresql 9.3 and ruby 2.1.2 and now:

avril14th@avril14th-ubuntu:~/src/mypopdesign/trunk$ rails c
Loading development environment (Rails 4.0.4)
2.1.1 :001 > DatabaseCleaner.clean
 => [#<DatabaseCleaner::Base:0x00000003b74ca8 @orm=:active_record, @strategy=#<DatabaseCleaner::ActiveRecord::Transaction:0x00000003b67440 @db=:default, @connection_class=ActiveRecord::Base>, @db=:default>] 
2.1.1 :002 > Mobilier.count
   (19.3ms)  SELECT COUNT(*) FROM "items" WHERE "items"."type" IN ('Mobilier')
   (19.3ms)  SELECT COUNT(*) FROM "items" WHERE "items"."type" IN ('Mobilier')
 => 55

**Comment by kai-kuchenbecker** [comment]
You have to define a strategy before running clean.
```ruby
DatabaseCleaner.strategy = :truncation, { except:  %w(public.schema_migrations) }
DatabaseCleaner.clean
```
Or `DatabaseCleaner.clean_with(:truncation, except: %w(public.schema_migrations))`

Both works for me.

**Comment by etagwerker** [comment]
Closing due to lack of feedback. 

@ghost Thanks for your comment!
