### ISSUE TITLE
truncation in capybara tests results in rspec freezing (while deletion works)

### ISSUE THREAD

**Issue by steookk** [DatabaseCleaner/database_cleaner#273]
I found out that this code (necessary to truncate in case we are testing with capybara) makes RSpec freeze right after running capybara tests, while the same code with :deletion strategy works smoothly. 
```ruby
    config.before(:suite) do
      DatabaseCleaner.strategy = :transaction
    end

    config.around(:each) do |example|
      if example.metadata[:type] == :feature
        example.run
        DatabaseCleaner.clean_with :truncation #ONLY DELETION WORKS!
      else 
        DatabaseCleaner.start
        example.run
        DatabaseCleaner.clean
      end
    end
```
As a matter of fact, the following code works for truncation, which makes me think that DatabaseCleaner.start must be run for truncation as well.
```ruby 
    config.before(:each) do
      DatabaseCleaner.strategy = :transaction
    end
    config.before(:each, :type => :feature) do
      DatabaseCleaner.strategy = :truncation
    end
    config.before(:each) do
      DatabaseCleaner.start #runs for both strategies
    end

    config.after(:each) do
      DatabaseCleaner.clean
    end
````
I don't know whether this is a bug or a some kinds of choice due to some reasons, however I felt it was worth pointing it out.

**Comment by karpah** [comment]
Unfortunately nothing here has fixed the problem in my app.

The test running sits there doing nothing, and when I start a Postgres console and check the `pg_stat_activity` table, I see the two connections sitting there, one active and one idle in transaction doing nothing. I don't know what's going on.

**Comment by lucashungaro** [comment]
@karpah Can you paste your spec_helper here?

**Comment by airatshigapov** [comment]
I am experiencing the same issue:

This config causes specs to freeze:

```ruby
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.around(:each) do |example|
    DatabaseCleaner.strategy = example.metadata[:js] ? :truncation : :transaction

    DatabaseCleaner.cleaning do
      example.run
    end
  end
end
```

Example provided by @lucashungaro fixes the issue, however I'm not sure why this happens. Any ideas?

**Comment by lucashungaro** [comment]
@airatshigapov It's probably an issue with around filters not working properly, so the transactions are never closed.

**Comment by ka8725** [comment]
May be this solution will help you: https://github.com/jnicklas/capybara/issues/1089#issuecomment-71767918

**Comment by claptimes5** [comment]
I believe this is an issue with the transactions not being closed. I had an issue deletion and truncation and was able to hack a solution by rolling back open transactions before deleting or truncating my tables

https://github.com/claptimes5/database_cleaner/commit/347b74b2ae2554e970ff3e9a5f63c3a6a4282f22

This should be taken care of in the `Transaction ` `clean` method, but I haven't had time yet to determine  a solution.

**Comment by DexterTheDragon** [comment]
I'm having the same experience that @lucashungaro mentions. Using an `around` hook ends up causing rspec to hang. Switching to a `before` and `after` hook works fine.

**Comment by tgaff** [comment]
Experiencing same behavior.  My config looks very much like airatshigapov's and I can confirm that dropping the `around` block in favor of `before` and `after` seems to resolve the issue.  The hang reported as a db deadlock in sqlite.  
rails 4.2.1 + database_cleaner 1.4.1 + capybara 2.4.4 + rspec 3.2.3

**Comment by RyanVasichko** [comment]
I managed to solve the problem by taking out `require 'capybara/rspec'` and using this for my database cleaning:

```
  config.before(:each) do |example|
    DatabaseCleaner.strategy = example.metadata[:js] ? :deletion : :transaction
    DatabaseCleaner.start
  end

  config.after(:each) do
    Capybara.reset_sessions!
    DatabaseCleaner.clean
  end
```

**Comment by alininja** [comment]
This thread helped me to find a fix for my problem, so I'll just post the fix here in case it's helpful for anyone:

```
config.around(:each) do |example|
    DatabaseCleaner.strategy = example.metadata[:js] ? :truncation : :transaction
    DatabaseCleaner.cleaning do
      example.run
    end
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
```

I'm not sure why the extra `DatabaseCleaner.clean` was necessary, but the dead lock issue came back without it.  I'm also not sure why it was necessary to run the spec inside the `DatabaseCleaner.cleaning` block; using just `DatabaseCleaner.start` and `DatabaseCleaner.clean` didn't work.

Just a bit more background on the issue I encounter since the above might not solve all the issues expressed on this thread:

Some feature specs were either taking too long or not exiting correctly, so it left a lock on the database, which caused all subsequent database-dependent specs to fail with this stack trace:

```
Failure/Error: Unable to find matching line from backtrace
ActiveRecord::StatementInvalid:
  Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: DELETE FROM `table_name`
```

**Comment by claptimes5** [comment]
Using 

```
config.around(:each) do |example|
  DatabaseCleaner.strategy = example.metadata[:js] ? :truncation : :transaction
  DatabaseCleaner.cleaning do
      example.run
  end
end
```

and the code in my pull request #364 I was able to resolve this issue where open transactions were left on various connections to the database. Can someone else see if this helps?

**Comment by karlingen** [comment]
@claptimes5 you deserve a medal. Thanks a bunch!! I've been pulling my hair of for the last 8 hours because of this issue. You PR fixed it. 
Added this to my Gemfile: 
```ruby
gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner', ref: 'b8edac6bd04fb89a267201fa8d47066d511fd9de'
```

**Comment by claptimes5** [comment]
@karlingen thanks!! I guess this issue can be closed? @etagwerker

**Comment by etagwerker** [comment]
@claptimes5 You're right sir. Thank you!

**Comment by rafaelsales** [comment]
Plans to have a version including this fix rolled out?

**Comment by rafaelsales** [comment]
@etagwerker @bmabey @JonRowe plans to have this fix rolled out? I'm currently using master in my gemfile :/

**Comment by karlingen** [comment]
@rafaelsales instead of using master you could lock it to a certain commit. 
I have it like this while waiting for a new version: 
```
gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner', ref: 'b8edac6bd04fb89a267201fa8d47066d511fd9de'
```

**Comment by etagwerker** [comment]
@rafaelsales Here it is: http://databasecleaner.github.io/2015/09/01/v1-5-0-is-out/ but @karlingen's suggestion should've worked before this release.
