### ISSUE TITLE
Failing specs after upgrade from 1.2 to 1.3

### ISSUE THREAD

**Issue by floydj** [DatabaseCleaner/database_cleaner#275]
I have a few features that require large amounts of data to be loaded into the test db before they're run.  I have tagged these specs as "slow".  What I'm trying to accomplish is that any feature spec tagged as "slow" will populate the db just once, use it for all specs in that feature and then clean the entire db after that feature is complete.

I have the following in my rails app, which works fine with database_cleaner 1.2 :

``` ruby
RSpec.configure do |config|

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :transaction
  end

  config.before(:each, :js => true) do
    DatabaseCleaner.strategy = :truncation
  end

  config.after(:all, :slow => true) do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.clean
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
end
```

These features are then setup like:

``` ruby
feature "GS Options page", :slow do
  before(:each) do
    DatabaseCleaner.strategy = :truncation, { except: %w[ products options models prices ] }
  end
end
```

After upgrading to database_cleaner 1.3, I'm now getting failures with these features.  The first few specs will pass ok, but then they all start failing with something like the following:

```
Failure/Error: Unable to find matching line from backtrace
     ActiveRecord::StatementInvalid:
       Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
```

The specs start passing again if I downgrade back to 1.2.

What can I do to make this work again?  Or is there a different strategy I should be using here?

**Comment by seban** [comment]
Have simmilar problem. My project Sinatra + ActiveRecord + RSpec after upgrade to 1.3 / 1.4 start failing with missing savepoint error.
My configuration is copy-pasted from README

```
config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end
end
```

Any hints?

**Comment by etagwerker** [comment]
@floydj @seban Do you experience this issue with 1.4.1? Please let me know.

**Comment by floydj** [comment]
@etagwerker I've moved on to a different strategy for various reasons, so I can't tell you if it works or not under the exact conditions of my original post. But FWIW, I am using 1.4.1 without any problems.

**Comment by seban** [comment]
@etagwerker currently when I update do 1.4.1 I got no errors.
