### ISSUE TITLE
DatabaseCleaner fails to honor strategy options(:only, expect) for non javascript cucumber scenarios

### ISSUE THREAD

**Issue by pisaruk** [DatabaseCleaner/database_cleaner#280]
Let suppose your features/support/env.rb has the following database_cleaner config:

```
begin
  require 'database_cleaner'
  require 'database_cleaner/cucumber'

  options = {:except => %w[genders, cities]}
  DatabaseCleaner.strategy = :truncation, options
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Around do |scenario, block|
  DatabaseCleaner.cleaning(&block)
end
```

You will notice that after running any javascript scenario every table, including the ones in the except options, will have been truncated.

One workaround would be to change your configuration, setting `javascritp_strategy`:

```
begin
  require 'database_cleaner'
  require 'database_cleaner/cucumber'

  options = {:except => %w[genders cities]}
  DatabaseCleaner.strategy = :truncation, options
  Cucumber::Rails::Database.javascript_strategy = :truncation, options

rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Around do |scenario, block|
  DatabaseCleaner.cleaning(&block)
end
```

I am quite convinced that it is a bug in cucumber-rails, because it is [forcing](https://github.com/cucumber/cucumber-rails/blob/2d57f6e3dd91b348121e33f45ff674bba3d141f1/lib/cucumber/rails/database.rb#L109) :truncation strategy for javascript scenarios ignoring any option supplied for the truncation strategy.

For now, one possible way to deal with this would be to change database_cleaner documentation accordingly.

**Comment by guiltry** [comment]
My data still truncated, what am I supposed to do?

**Comment by ardavis** [comment]
I am also encountering this issue, is anyone else? I am using the #javascript_strategory method and passing in `except` options.

**Comment by guiltry** [comment]
@ardavis you can manually delete selected table with hooks.
I've write a short article about it.

http://blog.guiltry.com/cucumber-and-database-cleaners-only-and-except-options/

**Comment by etagwerker** [comment]
@ardavis @pisaruk What version of databasecleaner are you using? If you use `master`, does it still happen? Please let me know.

**Comment by CBElizabeth** [comment]
@etagwerker I'm encountering this issue using database_cleaner 1.4.1.

**Comment by scooler** [comment]
@pisaruk I just ran into similar issue when when I debugged the database_cleaner I found issue in my configuration - also present here (so perhaps that's the cause here as well)
In the first part
```
options = {:except => %w[genders, cities]}
```
actually produces `options = ['genders,', 'cities']` - there shouldn't be a comma in %w notation (and there isn't one in examples in README - so it was just my "zealous comma-adding" - DOH )

**Comment by botandrose** [comment]
Closing due to age and inactivity. Feel free to reopen if this issue is still relevant.
