### ISSUE TITLE
cleaning functions too

### ISSUE THREAD

**Issue by ksudheer** [DatabaseCleaner/database_cleaner#289]
i created a function strip_tags though migration.
when i run tests, i think database cleaner clearing functions too?
How can i exclude database function deletion.

**Comment by kreba** [comment]
We are encountering this issue, too, since version > 1.3.0 
All the funcitons in the test database get cleared.
We are using Postgresql (9.4) and `use_transactional_fixtures = true` in RSpec (for a Rails app)
