### ISSUE TITLE
Got weird error with multiple ORM's in master branch

### ISSUE THREAD

**Issue by takashi** [DatabaseCleaner/database_cleaner#295]
I got `The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation (DatabaseCleaner::UnknownStrategySpecified)`

in my spec_helper

```ruby
config.before(:suite) do
    DatabaseCleaner.clean_with :truncation
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner[:mongoid].strategy = :truncation
end
```

Then I changed my gem file

`gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner'` to `gem 'database_cleaner', '~> 1.3.0'`,  the error never occurred. 

Is there any bug in master branch?

**Comment by gurix** [comment]
duplicate of #299

**Comment by etagwerker** [comment]
@takashi version 1.4.1 should fix this.

**Comment by takashi** [comment]
@etagwerker thank you for fixing!
