### ISSUE TITLE
Better cleaning method

### ISSUE THREAD

**Issue by cema-sp** [DatabaseCleaner/database_cleaner#296]
Hello!
In `cleaning` method in `database_cleaner/lib/database_cleaner/generic/base.rb` you have:  
```ruby
def cleaning(&block)
  start
  yield
  clean
end
```
There is recommendation in `factory_girl_rails` gem on adding linting like this:  
```ruby
begin
  DatabaseCleaner.start
  FactoryGirl.lint
ensure
  DatabaseCleaner.clean
end
```
So I thought that it would be nice to define `cleaning` method in that style for better error tolerance and for database to be cleaned anyway after partly executed `yield`:  
```ruby
def cleaning(&block)
  begin
    start
    yield
  ensure
    clean
  end
end

**Comment by claptimes5** [comment]
@etagwerker Want to close this since #311 was merged?

**Comment by cema-sp** [comment]
Sure, thank you)
