### ISSUE TITLE
Update changelog for 1.4.0

### ISSUE THREAD

**Issue by wli** [DatabaseCleaner/database_cleaner#321]
The History.rdoc file still has changes in 1.4.0 under development(master), so it's hard to tell what changed from 1.3.0 -> 1.4.0, versus what's actually under development.

https://github.com/DatabaseCleaner/database_cleaner/blob/master/History.rdoc

**Comment by axlekb** [comment]
:+1:

**Comment by etagwerker** [comment]
@wli If you submit a PR with 1.4.0's detail I'd be happy to review it and merge it. 

Here is the information: http://databasecleaner.github.io/2014/12/17/v1-4-0-is-out/ 

Thanks!

**Comment by vrinek** [comment]
PR has been merged. Thanks!
