### ISSUE TITLE
Option to not do RESTART IDENTITY in truncate

### ISSUE THREAD

**Issue by kikonen-fiksu** [DatabaseCleaner/database_cleaner#331]
Add option to not "RESTART IDENTITY" in truncate mode

Reason:
- Sequence needed to be used as id for external data storage, and same id cannot be thus reused in subsequent tests
- Tests are creating new partition tables, which are use ids from master tables in their names, thus ids cannot be reused in tests (since truncate can't remove this partition tables).

**Comment by etagwerker** [comment]
@kikonen-fiksu Could you provide more information? ORM, DBMS?

**Comment by botandrose** [comment]
Closing, due to lack of activity. Feel free to reopen with more information.
