### ISSUE TITLE
Mongoid 4.0

### ISSUE THREAD

**Issue by sebyx07** [DatabaseCleaner/database_cleaner#350]
i get this error when i try to run my specs
i'm using mongoid 4.0

    /home/sebi/.rvm/gems/ruby-2.2.0/bundler/gems/database_cleaner-bb608dd3ac6b/lib/database_cleaner/mongoid/truncation.rb:30:in `session': undefined method `default_session' for Mongoid:Module (NoMethodError)
    
    from /home/sebi/.rvm/gems/ruby-2.2.0/bundler/gems/database_cleaner-bb608dd3ac6b/lib/database_cleaner/moped/truncation_base.rb:26:in `collections'
        
    from /home/sebi/.rvm/gems/ruby-2.2.0/bundler/gems/database_cleaner-bb608dd3ac6b/lib/database_cleaner/moped/truncation_base.rb:14:in `clean'

    from /home/sebi/.rvm/gems/ruby-2.2.0/bundler/gems/database_cleaner-bb608dd3ac6b/lib/database_cleaner/base.rb:40:in `clean_with'

**Comment by uhomira** [comment]
Database-cleaner work for me with Mongoid 4 (4.0.0 and 4.0.2) as at 1.4.1 and as 1.3.0.
Are you using master branch?

**Comment by sebyx07** [comment]
thanks, it works now
