### ISSUE TITLE
JS related config setup info in README when using Database cleaner with RSpec

### ISSUE THREAD

**Issue by boddhisattva** [DatabaseCleaner/database_cleaner#355]
As per the latest database_cleaner gem do we need any additional config setup for JS tests ? This [blog by Avdi Grimm](http://devblog.avdi.org/2012/08/31/configuring-database_cleaner-with-rails-rspec-capybara-and-selenium/) for e.g., talks about  how they'd handle things differently when using Database cleaner for tests that involve JS. I do see that this blog is almost 3 years old but the current README from the database cleaner gem repo doesn't talk about how they'd handle specs that involve JS. Hence kindly throw some light on this.

Thanks.

**Comment by etagwerker** [comment]
@boddhisattva Is this section enough? https://github.com/DatabaseCleaner/database_cleaner#rspec-with-capybara-example 

It's a recent addition to the README. Please let me know.

**Comment by boddhisattva** [comment]
@etagwerker I'd like to sincerely apologise for not responding to your earlier question on this issue. I somehow missed replying to it, I'll try to be more careful in the future. Thank you and other contributors for their work on database cleaner. The updated README definitely adds more info on how they'd handle specs that invole JS.
