### ISSUE TITLE
Failing specs after upgrade from 1.3 to 1.4

### ISSUE THREAD

**Issue by danicuki** [DatabaseCleaner/database_cleaner#366]
When I upgraded from 1.3 to 1.4, some tests started failed, raising database errors for duplicate entries and other stuff. It seems database cleaner is not working properly in my project. Here is my rspec_helper file:

```
RSpec.configure do |config|
  config.filter_run_excluding :broken => true
  config.filter_run :focus => true
  config.run_all_when_everything_filtered = true
  config.infer_spec_type_from_file_location!

  config.infer_base_class_for_anonymous_controllers = false

  config.order = "random"

  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.strategy = :deletion, {except: %w[users]}
    DatabaseCleaner.clean_with(:truncation)
  end

  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end

end
```

**Comment by dimascyriaco** [comment]
I'm having the same problem. DatabaseCleaner 1.4.2, Rails 4.2.1, Capybara 2.4.4 and Rspec 3.3.0.

My configuration is the recommended for Capybara:

```
RSpec.configure do |config|
  DatabaseCleaner.logger = Rails.logger
  config.use_transactional_fixtures = false

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do |example|
    DatabaseCleaner.strategy= example.metadata[:js] ? :truncation : :transaction
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
end
```

@danicuki did you solved this?

**Comment by etagwerker** [comment]
@dimascyriaco @danicuki Could you test this code with `master` and let me know?

**Comment by dimascyriaco** [comment]
It's working again on 1.4.2. Don't know what fixed it.

Thanks anyway.

**Comment by carhartl** [comment]
I seem to have the same problem, using master didn't fix it.

**Comment by danicuki** [comment]
No fix

D

**Comment by carhartl** [comment]
I got it working using the transaction strategy and only truncation for acceptance testing (the Capybara scenario...). So it seems to be related to using truncation in unit tests... I was using 1.4.1.

**Comment by karlingen** [comment]
+1
