### ISSUE TITLE
Tables are getting cleaned when I don't want them to.

### ISSUE THREAD

**Issue by HuckyDucky** [DatabaseCleaner/database_cleaner#370]
I have a few tables in my test database that *MUST* remain seeded. I'm trying like hell to keep them seeded, because it takes about a half hour to seed them. I'm really going crazy here.

I'm trying to test a program in a custom test directory. I have this in my ```test_helper.rb``` file:

    class ActiveSupport::TestCase
      include Capybara::DSL
      ActiveRecord::Migration.check_pending!

      setup do
        DatabaseCleaner.start
      end
  
      teardown do
        DatabaseCleaner.strategy = :truncation, { except: %w[regions districts] }
        DatabaseCleaner.clean
      end
    end

I'm really, really confused here. All I know is, I've not found a way to preserve my data. These tables are much too large to put in seeds. They have to be specially populated. There must be some way to stop these tables from being deleted every single time.

**Comment by zwippie** [comment]
What happens if you move `DatabaseCleaner.strategy = :truncation, { except: %w[regions districts] }` to the `setup` block?

**Comment by HuckyDucky** [comment]
Nope, still deletes all tables.

**Comment by HuckyDucky** [comment]
You know, I put some debug statements in those setup and teardown blocks. They are not getting executed. If I put them main body of the class I see them. But nothing in those blocks. I wonder if that has something to do with it.

**Comment by HuckyDucky** [comment]
The object I'm trying to test is PORO. It is not a model. And I think that is why nothing is working. In Minitest, you can not test something other than a mailer, model, controller, view, etc. without weird logic-defying contortions.

**Comment by HuckyDucky** [comment]
OK, not a DatabaseCleaner issue, but I think this may help save somebody some time so I'll explain.

MiniTest does not test POROs by default. My helper code is fine. The ```setup``` and ```teardown``` methods were not running, because the object I'm testing is a PORO. POROs are not tied to AS::TC. As soon as I made the PORO subclass AR, everything worked as it was supposed to.

Subclassing AR is a hack. I am going to find a way to tie my POROs to AS::TC, although it's going to have to be something involving a test naming convention I suppose.
