### ISSUE TITLE
DatabaseCleaner not cleaning between otherwise-properly-running tests in `spec/lib` directory

### ISSUE THREAD

**Issue by jasonmklug** [DatabaseCleaner/database_cleaner#374]
I have a PORO class `EventInterface` which creates `Event` instances (`Event` is an ActiveRecord-backed class).  I have the `EventInterface` class in my `app/lib` directory, and configured Rails to load it.  All functions just fine.

For the sake of consistency, I created a corresponding `spec/lib` directory, and an `event_interface_spec.rb` file for my tests.

RSpec is running those tests in `spec/lib` just fine, and DatabaseCleaner is (and has been) performing dutifully across *everywhere else* my test suite.  But I ran into a problem where `Event` records created in `event_interface_spec.rb` are not cleaned out, and are affecting other tests (those other tests pass just fine when run in isolation).

I confirmed that lingering records were the culprit for the failures.  I then confirmed that DatabaseCleaner was not running between the tests in my `spec/lib` directory by moving `event_interface_spec.rb` (unchanged) from `spec/lib` to `spec/models`.  After the move, my entire suite passed.

I haven't found a way to configure DatabaseCleaner to explicitly include/exclude test files or directories — does one exist?  If not, is there a reason DatabaseCleaner wouldn't run between tests in my `spec/lib` directory, despite RSpec running those tests and despite DatabaseCleaner running properly everywhere else in my suite?

Here is my DatabaseCleaner-relevant config, for reference:

```ruby
RSpec.configure do |config|

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
    load "#{Rails.root}/db/seeds.rb"
  end

  config.before(:each, js: true) do
    DatabaseCleaner.strategy = :truncation
  end

  config.before(:each) do
    DatabaseCleaner.start
  end
  
  config.after(:each) do
    DatabaseCleaner.clean
  end
end
```

**Comment by karlingen** [comment]
Are you sure that the cleaner is not being ran at all when the files are located inside `spec/lib`? 
It could be an dependency order bug since moving the files to another folder would change the run order of the specs

**Comment by etagwerker** [comment]
@jasonmklug What does `event_interface_spec.rb` look like?

**Comment by jasonmklug** [comment]
Apologies for the slow response.

@karlingen nailed it — I was creating an `Event` record inside a `before(:all)` block, so DatabaseCleaner (rightly) didn't roll back the creation of that record between tests.

Moving the problematic spec file to `spec/models` still resulted in lingering `Event` records, but the move changed it's place in the order in which RSpec runs my spec files, such that existence of the lingering records didn't affect the few existing-record-sensitive tests in my suite.

Thanks.  Consider this one closed.
