### ISSUE TITLE
Please add support for mongo 2.0.6 driver

### ISSUE THREAD

**Issue by eriklott** [DatabaseCleaner/database_cleaner#379]
I can't seem to get DatabaseCleaner to function with the mongo 2.0.6 gem. We use the standalone mongo driver for all database interaction in a few of our services.

I've had to dig into the DatabaseCleaner::Base class to try to persuade it to integrate, as follows:

```
client = Mongo::Client.new("mongodb://127.0.0.1:27017/mydb")

db_cleaner = DatabaseCleaner::Base.new(:mongo)
db_cleaner.strategy = :truncation
db_cleaner.db = client.database
```

And it seems to almost work, however, database cleaner is now complaining with the following exception:

```
NoMethodError: undefined method `remove' for #<Mongo::Collection:0x007fa8e3c802d8>
    /Users/johndoe/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/mongo/truncation_mixin.rb:9:in `block in clean'
    /Users/johndoe/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/mongo/truncation_mixin.rb:9:in `each'
    /Users/johndoe/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/mongo/truncation_mixin.rb:9:in `clean'
```

Any help or direction would be appreciated.

**Comment by etagwerker** [comment]
@eriklott Could you check again with version 1.5.1?

**Comment by eric-simonton-sama** [comment]
I'm getting the same thing, using 1.5.1 and Mongo 2.1.2

**Comment by vpfaulkner** [comment]
Same here, also with 1.5.1 and Mongo driver 2.1.2

**Comment by eriklott** [comment]
@etagwerker . Still getting the same error with 1.5.1. DatabaseCleaner is calling a "remove" method during truncation, but the Mongo::Client doesn't respond to remove. As per the docs, you'll need to call 'delete_one' or 'delete_many' instead. 

Mongo Docs
https://docs.mongodb.org/ecosystem/tutorial/ruby-driver-tutorial/#ruby-driver-tutorial

**Comment by kylev** [comment]
It looks half-written. Is there a `lib/database_cleaner/mongo2/truncation.rb` laying around somewhere and not checked in?

**Comment by kylev** [comment]
I wrote #426 to fix it. It works with:

```ruby
client = Mongo::Client.new("mongodb://127.0.0.1:27017/mydb")

DatabaseCleaner[:mongo].strategy = :truncation
DatabaseCleaner[:mongo].db = client.database
```

Not sure how this would work with other systems (I'm using bare Mongo, no ORM).
