### ISSUE TITLE
Bump version? 

### ISSUE THREAD

**Issue by claptimes5** [DatabaseCleaner/database_cleaner#380]
There have been 50 commits to master since 1.4.1. Do you want to bump the version?

Thanks!

**Comment by etagwerker** [comment]
Yes, coming up soon.

**Comment by karlingen** [comment]
+1

**Comment by etagwerker** [comment]
@karlingen @claptimes5 Done! Here is the detail: https://github.com/DatabaseCleaner/DatabaseCleaner.github.io/pull/3

@claptimes5 Please let me know if the article has all the commits that you saw, or if I missed something. Thanks!

**Comment by karlingen** [comment]
Wonderful news! :clap: :clap: :clap:
