### ISSUE TITLE
Is it possible to reset_ids with transaction strategy?

### ISSUE THREAD

**Issue by eliduke** [DatabaseCleaner/database_cleaner#383]
I think maybe I am just confused on exactly how database_cleaner works, but I am having some problems with my tests because the auto-increment is not reseting. Here is the breakdown on my `spec_helper`.

```
RSpec.configure do |config|

  config.expect_with :rspec do |c|
    c.syntax = [:should, :expect]
  end

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
    DatabaseCleaner.strategy = :transaction
    load_seed_data
  end

  config.before(:all) do
    DatabaseCleaner.start
  end

  config.after(:all) do
    DatabaseCleaner.clean
  end

  config.example_status_persistence_file_path = "./spec/failures.txt"
  config.use_transactional_fixtures = true
  config.infer_base_class_for_anonymous_controllers = false
  config.order = "random"

  config.include FactoryGirl::Syntax::Methods
  config.include RSpec::Rails::RequestExampleGroup
  config.include Requests::JsonHelpers
  config.include Requests::Extensions

end
```

What I assume is happening there is that all tables are truncated and completely reset (auto-increment poised at 1), then all of the necessary spec seed data is loaded (that's it's own local method). Before each spec is run we start up DatabaseCleaner with a `transaction` strategy, which rolls back at the end of each spec when we clean. That all makes sense in my head, the problem is that I have some crazy runaway auto-incrementation going on.

I know that most people will tell me that it shouldn't matter, but for the sake of argument here, how can I make sure that my auto-increment is reset with a transactional strategy? Is that even possible?

I have put in a `binding.pry` in some places and checked the status of a specific table about 3/4 of the way through the test sweet. At that point there might be only 3 or 4 groups in the groups table, but the very first one has an `id` of 475. I know that it shouldn't matter, but there are some tests that are just so much easier to work with when I know that there are only 4 groups in the groups table (for that specific test) and they are id 1, 2, 3, and 4.

I thought that with transactions everything got rolled back and so the auto-increment shouldn't be going up at all. Am I missing something here? Is there any way to force transactions to reset ids?

**Comment by onyxraven** [comment]
Because you are using before/after(:all), the transaction isn't being closed around each test, so further down the run, it will have more and more data in the database.

**Comment by eliduke** [comment]
@onyxraven But will that reset the auto-increment back to zero?

**Comment by botandrose** [comment]
No, unfortunately not, and this happens at the database level, not ActiveRecord or database_cleaner. https://stackoverflow.com/questions/449346/mysql-auto-increment-does-not-rollback
