### ISSUE TITLE
Need more committers?

### ISSUE THREAD

**Issue by rafaelsales** [DatabaseCleaner/database_cleaner#388]
There are important issues that are in master already, but it's been a while we don't have versions rolled up to rubygems.

Perhaps increasing the team size is a good idea to not overwhelm you guys a lot @etagwerker @bmabey @JonRowe

**Comment by etagwerker** [comment]
@rafaelsales We are definitely open to new committers. 

If you see any issues, feel free to submit a PR. If you see any pull requests that you think that are ready to be merged, please let me know. 

For instance, what do you think about this PR? https://github.com/DatabaseCleaner/DatabaseCleaner.github.io/pull/3

Does it reflect the changes between 1.4.1 and 1.5.0? Feel free to comment over there.
