### ISSUE TITLE
Update History for 1.5.0

### ISSUE THREAD

**Issue by bmulholland** [DatabaseCleaner/database_cleaner#396]
Came to check what changed, but the history file only shows changes for 1.4.1. The commit messages aren't very descriptive, either, so I can't just use those.

**Comment by etagwerker** [comment]
@bmulholland You could use the information here: http://databasecleaner.github.io/

Could you submit a PR with this information?

**Comment by deXterbed** [comment]
Thanks alot for this awesome gem @etagwerker !!
