### ISSUE TITLE
1.5.1 is not available on rubygems

### ISSUE THREAD

**Issue by gurix** [DatabaseCleaner/database_cleaner#397]
```ruby
gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner'
```
Fetching from github solves the problem so that I can run it now with mongoid 5.0 as temporary solution.

**Comment by etagwerker** [comment]
@gurix Not really an issue. We will release 1.5.1 soon. In the mean time, you can tie your build to a specific commit in `master`

**Comment by gurix** [comment]
ok, thanks for info
