### ISSUE TITLE
The 'truncation' strategy does not exist for the mongoid ORM!

### ISSUE THREAD

**Issue by giannileggio** [DatabaseCleaner/database_cleaner#402]
Hi guys, I'm getting this error when trying to use last mongoid version
[...]/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:139:in `rescue in orm_strategy': The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation (DatabaseCleaner::UnknownStrategySpecified)

My gems:
database_cleaner (1.5.0)
mongo (2.1.1)
mongoid (5.0.0)

In spec_helper I have:

config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.clean_with(:truncation)
 end

**Comment by giannileggio** [comment]
The same happens if I use mongoid 4 with database_cleaner 1.5
The only way to have them working is to use mongoid 4 and database_cleaner 1.4

**Comment by Elyasin** [comment]
+1 for raising this issue

**Comment by ahmet** [comment]
+1 with mongoid 5 and database cleaner 1.5

**Comment by jpmckinney** [comment]
Seems to be fixed in master.

**Comment by alexsanford** [comment]
I'm also seeing it fixed in master. Looks like the version number was bumped to 1.5.1, but the gem was never released (`gem 'database_cleaner', '~> 1.5.1'` does not work).

Are there any plans to release this version? Currently I have it working in my Gemfile using a git reference, but a version number would be better.

**Comment by vitalis** [comment]
#390

**Comment by noiseunion** [comment]
+1

**Comment by alexkravets** [comment]
+1 mongoid 5.0, database_cleaner 1.5.0

**Comment by etagwerker** [comment]
Fixed in version 1.5.1.
