### ISSUE TITLE
Elastic search support

### ISSUE THREAD

**Issue by kimegede** [DatabaseCleaner/database_cleaner#403]
Would be lovely to have this supporting Elastic Search as well.

**Comment by dapicester** [comment]
A PR is on my TODO list, in the meanwhile I do something like this, in `test_helper`:
```ruby
def es_delete_all
  Elasticsearch::Persistence.client.indices.delete index: '_all'
end
```
and then call it in an `after` block or `teardown` method.

Let me know if it works for you.

**Comment by mathieujobin** [comment]
+1

**Comment by dduft** [comment]
:+1:

**Comment by fidalgo** [comment]
Just beware that the @dapicester solution will remove all the indices for all environments.

**Comment by dapicester** [comment]
@fidalgo I've not been using this for a long time and I cannot verify what you wrote.
However, I recall that I have two ElasticSearch instances running, one for `develop` environment and one for `test`, so whatever I do with the `test` instance should not affect the `develop` instance.

**Comment by fidalgo** [comment]
@dapicester also using https://github.com/ankane/searchkick the indices have a suffix of the environment, like `users_test`

**Comment by etagwerker** [comment]
@kimegede Good idea! If someone wants to implement a new ORM, they can follow the instructions being discussed over here: https://github.com/DatabaseCleaner/database_cleaner/issues/628
