### ISSUE TITLE
mysql 0.4.1 throws exception

### ISSUE THREAD

**Issue by alexandru-calinoiu** [DatabaseCleaner/database_cleaner#404]
With the database_cleaner 1.5.1 and mysql 0.4.1 I get the following exception:

```
 Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
```

**Comment by st0012** [comment]
I think this issue may not caused by database_cleaner, it's caused by the mysql2 version you're using.
See: https://github.com/rails/rails/issues/21544

**Comment by alexandru-calinoiu** [comment]
You are right. Thank you.

**Comment by st0012** [comment]
:smile:
