### ISSUE TITLE
rspec issue with mongo 3.0.7 using wired tiger storage and database cleaner 1.5.1

### ISSUE THREAD

**Issue by atulaltizon** [DatabaseCleaner/database_cleaner#409]
Hi,
I am having issues running rspec in the above mentioned combination. The 'collections' method in the mongo2/truncation mixin.rb returns an empty list when mongo is running on 'wired tiger' storage engine. 
I replaced with the following code:

database.collections.collect { |c| c.namespace.split('.',2)[1] }

This seems to work for both mmapv1 and wired tiger

Kindly fix this.

**Comment by dmitrypol** [comment]
atulaltizon - thank you SOOO much for the fix.  I just did a PR by just copying and pasting your idea but the credit belongs to you.

**Comment by atulaltizon** [comment]
You are welcome!

**Comment by akirsch** [comment]
Hi.

When it is possible to get an update of the gem with this fix?

**Comment by dmitrypol** [comment]
the fix is merged into master so you could point your Gemfile at github.  It would be nice to get updated gem but I am sure it's maintainer has a life outside of open source ;-).

**Comment by akirsch** [comment]
thx for the fast feedback :) i hope the maintainer has this life outside of open source. :) 
via git it works now all right :+1:

**Comment by siman-man** [comment]
According to this [History](https://github.com/DatabaseCleaner/database_cleaner/blob/master/History.rdoc#bug-fixes-5), this issue seem to has already been solved. Is this issue closed?

```
* @dmitrypol fixed issue #409
```
