### ISSUE TITLE
Rails 5/tables deprecation warning

### ISSUE THREAD

**Issue by jasnow** [DatabaseCleaner/database_cleaner#412]
After upgraded one of my repos to Rails 5, I am getting this warning during "rake" run:
 * DEPRECATION WARNING: #tables currently returns both tables and views.
   This behavior is deprecated and will be changed with Rails 5.1 to only
   return tables. Use #data_sources instead. (called from
   database_cleaner_table_cache at .../.rvm/gems/ruby-2.2.3@2.2.3/bundler/gems/
   database_cleaner-b87f00320f8a/lib/database_cleaner/active_record/truncation.rb:30)

Researched the message and found this background information:
 * https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb
 * https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb
 * https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md

So I looked at line 30 cited in the above message:
 * database_cleaner-b87f00320f8a/lib/database_cleaner/active_record/truncation.rb

and changed it from:
 * @database_cleaner_tables ||= tables

To:
 * @database_cleaner_tables ||= data_sources

And the message went away. Hope this helps.

**Comment by etagwerker** [comment]
@jasnow Thanks! Closed by #415
