### ISSUE TITLE
Rails 5 ActiveRecord::InternalMetadata.table_name

### ISSUE THREAD

**Issue by metaskills** [DatabaseCleaner/database_cleaner#422]
Was updating an app to the latest Rails 5 and wanted to drop a note that there appears to be a new schema meta data table. I had to do this:

``` ruby
DatabaseCleaner.clean_with :truncation, except: [ActiveRecord::InternalMetadata.table_name]
```

Normally this table is called `active_record_internal_metadata`, but using the class' table_name method seems to be the right way to look it up in case someone adds a prefix or reconfigures the name. I took a look into the source and saw you had `schema_migrations` hard coded to that name. Perhaps it too should be updated to use `ActiveRecord::SchemaMigration.table_name` for the same reasons?

**Comment by doits** [comment]
+1, otherwise I always get a `ActiveRecord::NoEnvironmentInSchemaError` after each run.

**Comment by eliotsykes** [comment]
Seen with Rails 5.0.0.beta1.1, database cleaner 1.5.1. Database cleaner will execute `DELETE FROM "active_record_internal_metadatas"` unless the `except: ...` option is specified [as described above](https://github.com/DatabaseCleaner/database_cleaner/issues/422#issue-128444021)

**Comment by stevenharman** [comment]
Looks like this will be closed with #487 ships.

**Comment by stevenharman** [comment]
Lies... now we'll need to wait for https://github.com/DatabaseCleaner/database_cleaner/pull/491 to land and ship.

**Comment by stevenharman** [comment]
@etagwerker, I think we can close this as of #490.

**Comment by etagwerker** [comment]
@stevenharman 👍
