### ISSUE TITLE
undefined local variable or method `data_sources'

### ISSUE THREAD

**Issue by shanys8** [DatabaseCleaner/database_cleaner#435]
Hi
I am getting this error
in `database_cleaner_table_cache': undefined local variable or method `data_sources'
when I change in truncation.rb this line
@database_cleaner_tables ||= data_sources
to this
@database_cleaner_tables ||= tables
the error is not happening and tests are running.

Can you tell me what seems to be the problem?

**Comment by etagwerker** [comment]
@shanys8 What version of ActiveRecord and DatabaseCleaner are you using? 

`data_sources` was introduced here: https://github.com/DatabaseCleaner/database_cleaner/commit/430a9574d263b890eddb5af7d176c7f3ba74e233 and it's only available in `master`

**Comment by shanys8** [comment]
activerecord-4.1.2 and database-cleaner 1.5.1

**Comment by etagwerker** [comment]
@shanys8 Could you try with `master` and post back here?

**Comment by shanys8** [comment]
Yeah, that works. (included the gem in my gemfile through its git path)
Are you going to create a release from master as a new version?

**Comment by etagwerker** [comment]
@shanys8 Yes, I just released 1.5.2: http://databasecleaner.github.io/2016/04/17/v1-5-2-is-out/

Thanks!
