### ISSUE TITLE
Support WiredTiger (Mongo >= 3.2)

### ISSUE THREAD

**Issue by the-robear** [DatabaseCleaner/database_cleaner#438]
When using the truncate strategy, database_cleaner does not clean mongo databases using WiredTiger (WT). When running the same mongo version using MMAPV1, database_cleaner works fine. This is all using Mongoid 5.1.2

Upon inspecting the mongo logs for WT we see that transactions are attempted in the following order:

```
WT begin_transaction
WT commit_transaction
...
[[ db insert occurs ]]
...
WT begin_transaction
WT rollback_transaction
```

There are no remove calls in the WT logs, whereas we see them in the MMAPV1 logs.

As an immediate action, I think we could put a warning in the README saying that Mongo 3.2 using WiredTiger is not currently supported.

**Comment by etagwerker** [comment]
@the-robear Have you tried using the truncation strategy? Please share the code that you are using to reproduce this. 

Mongoid only supports the truncation strategy. See: https://github.com/DatabaseCleaner/database_cleaner/#supported-databases-libraries-and-strategies

**Comment by the-robear** [comment]
@etagwerker Yes - I am using truncation. Will post tomorrow

**Comment by the-robear** [comment]
@etagwerker Ok, so this happens on multiple machines / environments, all running >= Mongo 3.2 under WildTiger.

Code-wise, I guess the configuration is what you're looking for?

```ruby
begin
  require 'database_cleaner'
  require 'database_cleaner/cucumber'
  DatabaseCleaner[:mongoid].strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Around do |scenario, block|
  DatabaseCleaner.cleaning(&block)
end
```

Our Cukes run fine when we run Mongo with the storage engine flag:  `mongod --storageEngine=mmapv1`, which uses the old storage engine. It is only when WildTiger is used.

Let me know if you need more information!

**Comment by AndreaBeggiato** [comment]
Any news on this argument? We have the same issue

**Comment by marcusbuffett** [comment]
Updating to the latest version of database_cleaner (1.5.3) fixed all issues I had re: database_cleaner and WT. Think this can be closed.
