### ISSUE TITLE
DatabaseCleaner not cleaning (Mongoid)

### ISSUE THREAD

**Issue by ekyfauzi** [DatabaseCleaner/database_cleaner#439]
Hi, I got problem, DatabaseCleaner not clean database at all.
I getting stuck for few days.
Almost exactly the same setup. No idea why it's not, can't track it down.
Here is my `spec_helper.rb`
```ruby
  config.before(:suite) do
    DatabaseCleaner[:mongoid].strategy = :truncation
    load Rails.root + "db/seeds.rb"
  end

  config.before(:each) do
    DatabaseCleaner[:mongoid].start
  end

  config.after(:each) do
    DatabaseCleaner[:mongoid].clean
  end
```

I use:
```
ruby (2.2.2)
rails (4.2.5) 
mongoid (4.0.2)
mongoid-rspec (2.1.0)
rspec-rails (3.3.3)
database_cleaner (1.3.0)
```

Anyone can help me?

**Comment by etagwerker** [comment]
@ekyfauzi Have you tried upgrading to the latest version of `database_cleaner`? It's currently at 1.5.2.

**Comment by ekyfauzi** [comment]
Hey @etagwerker, I've upgrading `database_cleaner` to `1.5.2` and it's work!
Thanks.

**Comment by etagwerker** [comment]
@ekyfauzi Great, thanks! 👍
