### ISSUE TITLE
TRUNCATE statements in logs appear intermittent

### ISSUE THREAD

**Issue by jasonfb** [DatabaseCleaner/database_cleaner#449]
We have a test suite that has unit tests in trasnaction strategy and feature specs in truncation strategy. One really odd thing I've seen along with another developer is that when tailing the test log (```log/test.log```), sometimes you see ``` TRUNCATE ...``` statements and some other times you don't

It seems to us to be completely random and non-deterministic. The lack of TRUNCATE output statements makes it more difficult to debug and this non-deterministic behavior means there is some part that is acting in a race condition way or is somehow intermittent in a way we do not understand. 

my full gemfile.lock is as follows:

https://gist.github.com/jasonfb/9b8893f102596ed7756bf46aaae82983

we are on database_cleaner 1.4.0 with rspec-core 3.5.0.beta4

**Comment by etagwerker** [comment]
@jasonfb Did you try this? https://github.com/DatabaseCleaner/database_cleaner#debugging

**Comment by jasonfb** [comment]
We debugged this down to JSON endpoints that had cache-control headers on them. Capybara holds onto cache responses between tests. I documented this in my blog post here: https://medium.com/@jaflebol/capybara-taming-the-hydrochoerus-8fcd28d70787#.1qmna29ok
