### ISSUE TITLE
Excluding tables from the database clean

### ISSUE THREAD

**Issue by anathematic** [DatabaseCleaner/database_cleaner#45]
Howdy,
I've been digging through the code and found the except / only options but I don't quite understand how to use them.
I've tried Database.clean(:except => [:bar, :foo]) with no luck - my ruby-fu wasn't quite strong enough to understand what was going on in the code.

Cheers!
Thomas

**Comment by sarojkh** [comment]
@robacarp Thanks! Saved my day.
@bmabey Should not the fact that `clean_with` doesn't share the excluded tables passed in `except` in `strategy=` be included in the README? It would be more obvious.

**Comment by slhck** [comment]
I'm getting this now:

```
Failure/Error: DatabaseCleaner.strategy = :transaction, { except: keep_tables }

ArgumentError:
  Options are not available for transaction strategies. 
```

**Comment by botandrose** [comment]
@slhck Are you using ActiveRecord, or some other ORM?

**Comment by slhck** [comment]
This is using ActiveRecord in Rails 6.0, yes.

**Comment by botandrose** [comment]
@slhck Yes, I can confirm that database_cleaner does not support the `except` option for the ActiveRecord transaction strategy. This makes sense when you think about how transactions work... its just reverting the database back to a checkpoint, more or less. If you want to explicitly specify tables to ignore, switch to the truncation strategy. I hope this helps.

**Comment by slhck** [comment]
That's fine, thanks for checking! It's just that the above example is no longer valid (but can be easily found online... That's how I can here.)
