### ISSUE TITLE
ActiveRecord schema_migrations being truncated because of public. schema

### ISSUE THREAD

**Issue by bradurani** [DatabaseCleaner/database_cleaner#454]
Our postgres database uses the schema `public`. DatabaseCleaner is supposed to not truncate `schema_migrations`, but in our case it was. When I debugged the code, I found that in `DatabaseCleaner::ActiveRecord::Truncation.tables_to_truncate`, `tables_in_db` returns table names with the schema prefix (`public.schema_migrations`), but `@tables_to_exclude` contains `schema_migrations`.
I fixed this by doing `DatabaseCleaner.strategy = :truncation, { except: 'public.schema_migrations' }` in my spec helper, but its seems like a bug, so I thought I'd report it.

**Comment by Fornacula** [comment]
Same case for me.

**Comment by etagwerker** [comment]
@Fornacula @bradurani I believe this has been fixed in the latest version. Is this still happening with version 1.6.1? Please let me know.

**Comment by Fornacula** [comment]
My bad - I was using older version (1.5.3) :)

**Comment by etagwerker** [comment]
@Fornacula Great, thanks!
