### ISSUE TITLE
New gem release

### ISSUE THREAD

**Issue by davedash** [DatabaseCleaner/database_cleaner#460]
Could you release a new version of the gem?  There's a few changes that I'd like to use, specifically with the `NullStrategy` that aren't in 1.5.3

**Comment by danielroseman** [comment]
I see that the version number has been bumped to 1.6.0 but there hasn't actually been a release; Rubygems is still showing the latest version as 1.5.3. With the release of Rails 5.1 this gem is now showing a deprecation warning; please can the latest version be pushed?

**Comment by etagwerker** [comment]
`database_cleaner` version 1.6.1 was released last week: http://databasecleaner.github.io/2017/05/09/v1-6-1-is-out/
