### ISSUE TITLE
truncating fails with Sequel

### ISSUE THREAD

**Issue by RedFred7** [DatabaseCleaner/database_cleaner#463]
I'm running RSpec tests with DatabaseCleaner on the following Sequel models
```
class User < Sequel::Model
      one_to_many :memberships
      many_through_many :accounts, [[:memberships, :user_id, :account_id]]
end

class Account < Sequel::Model 
      one_to_many :memberships
      many_through_many :users, [[:memberships, :user_id, :account_id]]
end

class Membership < Sequel::Model
      many_to_one :account
      many_to_one :user
end
```

when I run the tests, I get the following error:

```
An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean_with(:truncation)

Sequel::DatabaseError:
  Mysql2::Error: Cannot truncate a table referenced in a foreign key constraint (`account_users`.`memberships`, CONSTRAINT `memberships_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `account_users`.`accounts` (`id`))
```

My DatabaseCleaner setup is:

```
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end
```

Truncation is one of the methods supported by DatabaseCleaner with Sequel, so this should work. Any ideas why it doesn't ?

**Comment by baschtl** [comment]
@RedFred7 Have a look at https://github.com/DatabaseCleaner/database_cleaner/issues/286. Sequel adds foreign key constraints automatically which means you cannot just truncate tables. But you can workaround the issue with disabling the key checks temporarily.

**Comment by RedFred7** [comment]
Thanks @baschtl, I've already done that, as a workaround.  But isn't this something DatabaseCleaner should be doing itself though? I mean if it supports truncation shouldn't it be also disabling referential integrity checks? In any case, I'll close this issue as duplicate to [#286](https://github.com/DatabaseCleaner/database_cleaner/issues/286), thanks.
