### ISSUE TITLE
db:reset for cleaning strategy

### ISSUE THREAD

**Issue by mathieujobin** [DatabaseCleaner/database_cleaner#464]
Hello,

sorry to be asking a question here if this is not the right place.
when having 200+ tables, the truncation strategy takes so much time.
I am looking for a way to speed this up and I am thinking, while not dropping the whole thing.
`rake db:drop db:test:prepare` or maybe `rake db:reset` is usually quite fast.

shouldn't it be too hard to implement in database cleaner, what do you guys think of this?

**Comment by randoum** [comment]
You don't need database cleaner for this. Simply call the related rake tasks from a `before(:suite)` block

**Comment by mathieujobin** [comment]
thanks
