### ISSUE TITLE
Rails 5.1 removes ActiveRecord::Migrator.schema_migrations_table_name

### ISSUE THREAD

**Issue by activefx** [DatabaseCleaner/database_cleaner#476]
ActiveRecord truncation strategy fails on Rails 5.1 because `ActiveRecord::Migrator.schema_migrations_table_name` has been replaced with `ActiveRecord::SchemaMigration.table_name`

**Comment by djolereject** [comment]
I'm getting it too.
On starting tests, this message appears:

```
An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean_with :truncation

NoMethodError:
  undefined method `schema_migrations_table_name' for ActiveRecord::Migrator:Class
````

**Comment by jasnow** [comment]
FYI: Think this has gone away: https://github.com/rails/rails/commit/96aa18974adf7321f265eafbdfe74c7c6e007cb0

**Comment by terry90** [comment]
+1 must fix this

**Comment by jasnow** [comment]
FYI: Now we are getting: **DEPRECATION WARNING: schema_migrations_table_name 
is deprecated and will be removed from Rails 5.2** - Probably another issue. FYI

**Comment by etagwerker** [comment]
@jasnow This is now fixed in `master` - Soon I'll release 1.6.0 with @activefx's fix.

**Comment by jasnow** [comment]
Thanks

**Comment by morgoth** [comment]
Can we have a release? Rails 5.1 is out and it outputs this warning when using stable version of database cleaner

**Comment by etagwerker** [comment]
Just released a new version of database_cleaner with this fix: http://databasecleaner.github.io/2017/05/04/v1-6-0-is-out/ 👍

**Comment by tonyc** [comment]
Thank you!
