### ISSUE TITLE
DatabaseCleaner with before(:all)

### ISSUE THREAD

**Issue by ajmiciano** [DatabaseCleaner/database_cleaner#489]
I am using the common configuration of DatabaseCleaner and I came across a problem.
When I use `before(:all)`, the DatabaseCleaner does not clear the records created inside the hook.

Has anyone seen this?

Configuration:
  ```
config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
    DatabaseCleaner.strategy = :transaction
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
```

My hook:
```
before(:all) do
  # create a entry
end
```

**Comment by mauro-oto** [comment]
@ajmiciano your DatabaseCleaner config hooks into `:each`, for RSpec's `before(:each)` blocks, but there's no mention of `config.before(:all)`. 

Usually `before(:all)` is something you want to avoid. The reason being that anything you create in a `before(:all)` by default is persisted throughout all of your test suite, bleeding into other tests. 

You need to make sure to either clean up after it with an `after(:all)` hook in your tests, or setup DatabaseCleaner to do it for you with something like: 

```
config.before(:all) do
  DatabaseCleaner.start
end

config.after(:all) do
  DatabaseCleaner.clean
end
```

There's a good article about it here: http://renderedtext.com/blog/2012/10/10/cleaning-up-after-before-all-blocks.
