### ISSUE TITLE
Before clean hook

### ISSUE THREAD

**Issue by knightq** [DatabaseCleaner/database_cleaner#494]
It would be very useful to have the chance to hook into the code execution of `clean` method to prevent - through an hook (via config) - the execution.

The use case is - for example - the bad execution of test in the wrong execution environment (read: production).

What if you mistakenly run your test suite against the wrong DB?
It happens that `database_cleaner` does its job and _delete all production data_ as if it was testing data.

Using a hook that runs just before the "non returning point" would make possible to check the db connection to ensure that the connection exists with the proper DB.

Make some sense?

**Comment by botandrose** [comment]
I believe this has been addressed by the safeguards introduced in v1.7.0: https://github.com/DatabaseCleaner/database_cleaner#safeguards
