### ISSUE TITLE
Database Cleaner truncating the wrong environment DB

### ISSUE THREAD

**Issue by rdlu** [DatabaseCleaner/database_cleaner#503]
I have found a weird issue when using database cleaner in one of my rspec'd projects.

If you set a url: in /development section/ of database.yml, it ignores the socket and database strings of /test section/.

In my case I mistakenly truncated the homologation database running rspec with guard, because I was manually testing a corner condition using that homolog url as development.

So be careful if you mix database / socket (local one) with url'ed remote database. It gives preferences to the URL regardless of what section you put on database.yml.

The gem version here is 1.6.1.

My database.yml configuration:

    development:
      <<: *default
      url: <%= ENV['DATABASE_URL'] %>

    test:
      <<: *default
      database: my_database_test
      socket: /tmp/mysql.sock

Is there a way to fix/workaround this behavior? Thanks!

**Comment by etagwerker** [comment]
@rdlu Hi, I'm not able to reproduce this issue. Could you submit more information? 

I assume you're using active_record. If so, what version? 

Also, could you submit the code that you're using to setup database_cleaner?

Thanks!
