### ISSUE TITLE
Duplicate Key for first time rspec

### ISSUE THREAD

**Issue by Aravind99** [DatabaseCleaner/database_cleaner#509]
This error occured for the first time I ran (rspec) and then there is no error.
Mysql2::Error: Duplicate entry '1' for key 'PRIMARY': INSERT INTO `products` (`title`, `amount`, `coutry_id`, `product_type`, `id`, `created_at`, `updated_at`) VALUES ('samsung LED TV', 50000.0, 1, 'Luxury', 1, '2017-11-09 16:22:59', '2017-11-09 16:22:59')

```ruby
# file => spec/support/factory_bot.rb
RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods
  config.before(:suite) do
    begin
      DatabaseCleaner.start
    ensure
      DatabaseCleaner.clean
    end
  end
end
```
```ruby
# file => spec/factories.rb
FactoryBot.define do
  factory :product do
    title 'samsung LED TV'
    amount '50000'
  end
end
```

```ruby
# file => spec/models/product.rb
require 'rails_helper'

RSpec.describe Product do
  let(:product) { create(:product) }

  context 'sold_products' do
    it 'will return array of sold products' do
      expect(Product.sold_products).to eq [product]
    end
  end 
end
```

**Comment by etagwerker** [comment]
@Aravind99 It seems that you're starting with a dirty database. Please try using the code in this example: https://github.com/DatabaseCleaner/database_cleaner#rspec-example

**Comment by Aravind99** [comment]
@etagwerker Thanks :+1:
