### ISSUE TITLE
warning: instance variable @table_stats_query not initialized

### ISSUE THREAD

**Issue by isacaraujo** [DatabaseCleaner/database_cleaner#516]
Always I run the test with `:deletion` strategy, I got this error:

```
database_cleaner-1.6.2/lib/database_cleaner/active_record/deletion.rb:66: warning: instance variable @table_stats_query not initialized
```

My environment:

- OSX 10.13.2 (17C88)
- ruby 2.4.2p198
- rspec (3.7.0)
- mysql2 (0.4.10)
- database_cleaner (1.6.2)
- activerecord (5.1.4)

Workaround:

As workaround, I fixed as follow:

```
if @cache_tables && defined?(@table_stats_query) && !@table_stats_query.nil?
  return @table_stats_query
else
```

**Comment by etagwerker** [comment]
@isacaraujo Thanks for reporting this! Could you submit a PR with the patch?
