### ISSUE TITLE
Disable DatabaseCleaner for specific specs

### ISSUE THREAD

**Issue by zedtux** [DatabaseCleaner/database_cleaner#519]
I'm testing a Rails application using DatabaseCleaner and all is fine until I started to test a service (a Plain-Old Ruby Object (PORO)) and have to always wait on DatabaseCleaner to truncate all the tables while the service is not persisting any data.

So is there a way to say that for my service, I don't need at all DatabaseCleaner and so get the tests running faster?

**Comment by mauro-oto** [comment]
@zedtux if you use RSpec, you might be able to achieve this by tagging your test with something like `service: :true` or `skip_db_cleaner: :true`, and then in your Database Cleaner config in `spec_helper` or `rails_helper` do something like: 

```
config.before(:each) do |example|
  unless example.metadata[:skip_db_cleaner]
    DatabaseCleaner.start
  end
end
```

**Comment by zedtux** [comment]
Thank you @mauro-oto, I'll try that soon and let you know.

**Comment by zedtux** [comment]
@mauro-oto it is working fine, I just changed the `:true` to `true`. 👍
