### ISSUE TITLE
active_record/truncation.rb missing Oracle adapter from to load.

### ISSUE THREAD

**Issue by oscarAtNava** [DatabaseCleaner/database_cleaner#524]
On line 7 of active_record/truncation.rb the list of connection adapters is missing the oracle_enhanced_adapter. Without this adapter name in the list the code in line 224 fails to load the OracleAdapter decorator. As a consequence when you try to use the cleaner with an Oracle DB you get a NotImplemented error when the truncate_table method is executed.

I modified my local copy of database_cleaner and was able to successfully truncate tables in my Oracle DB.

Original code starting in line 5:
`
#Load available connection adapters`
`
%w(
  abstract_mysql_adapter postgresql_adapter sqlite3_adapter mysql_adapter mysql2_adapter`
`
).each do |known_adapter|
`

Modified code :
`
#Load available connection adapters`
`
%w(
  abstract_mysql_adapter postgresql_adapter sqlite3_adapter mysql_adapter mysql2_adapter oracle_enhanced_adapter`
`
).each do |known_adapter|
`

Let me know if you have any questions or need additional information.

**Comment by etagwerker** [comment]
@oscarAtNava That is quite clear. Could you please submit a PR with your patch?

**Comment by oscarAtNava** [comment]
Will do. I need to be added as contributor?

**Comment by etagwerker** [comment]
@oscarAtNava It's not necessary. You need to fork the repository, create a branch, commit the change to the branch, push to your forked repo, and finally open a PR. 

Here is more info here: https://github.com/DatabaseCleaner/database_cleaner/blob/master/CONTRIBUTE.markdown

Considering it's such a small change, it won't be necessary to add a test.

**Comment by oscarAtNava** [comment]
Ok, I did create a branch but missed the forking step. Will do.

**Comment by oscarAtNava** [comment]
https://github.com/DatabaseCleaner/database_cleaner/pull/542

**Comment by oscarAtNava** [comment]
My pull request is green. When will it be merged to master and available for us to use in our app?

**Comment by etagwerker** [comment]
@oscarAtNava Just merged #542. You can test that it works using `master` now. Thanks!
