### ISSUE TITLE
DatabaseCleaner.clean hanging

### ISSUE THREAD

**Issue by blevine** [DatabaseCleaner/database_cleaner#527]
Environment:
- Ruby 2.5.1
- Rails 5.2.0
- MacOS 10.13.2
- PostgresQL 9.4.0
- DatabaseCleaner 1.6.2

`DatabaseCleaner.clean` hangs.  This occurs regardless of where I put the clean call. See code below. The `clean` call from the `before(:all)` block never returns.  If I remove this call, the spec(s) complete, but the spec command never exits because the `clean` call in the `after(:all)` block hangs.

We just recently upgraded to ruby 2.5.1 and Rails 5.2.0 so I suspect this and/or differences in the PostgresQL driver are causing this problem, but can't prove that yet.

Code from spec shared_context:

```DatabaseCleaner.strategy = :truncation, { pre_count: true }
  before(:all) do
    puts "before DatabaseCleaner.start"
    DatabaseCleaner.start
    puts "after DatabaseCleaner.start"
    DatabaseCleaner.clean
    puts "after DatabaseCleaner.clean"
    ...

  after(:all) do
    DatabaseCleaner.clean
  end
```

**Comment by blevine** [comment]
Additional information.  Just noticed in the log output that the hang appears to happen when a transaction is being started.  I see the following as the last line output just before the hang:

   `(0.2ms)  BEGIN`

**Comment by etagwerker** [comment]
@blevine Supposedly you don't need `database_cleaner` with Rails 5.2.0. Did you try running your spec without `database_cleaner`?

**Comment by blevine** [comment]
@etagwerker I create a couple of models in my before(:all) that are used by each example and those need to be removed to avoid unique violations the next time the specs are run.  Yes I suppose I could delete each of those fixture models in the after(:all), but I was hoping not to have to do this.  What is it about Rails 5.2.0 that makes DatabaseCleaner not required?

**Comment by etagwerker** [comment]
@blevine I believe they added support to Rails (starting with 5.1.0). You can find more information here: 

- http://guides.rubyonrails.org/5_1_release_notes.html#system-tests
- https://github.com/rails/rails/pull/26703

As an example, here you can see how `solidus` adjusted their test code accordingly: https://github.com/jhawthorn/solidus/commit/9be29352398bee088d216ae11289b4167543942d

**Comment by blevine** [comment]
False alarm.  It seems that either my test database became corrupted or something went wrong with my instance of Postgres.  After some additional testing, it seems that  number of ActiveRecord calls were hanging.  Re-starting Postgres and re-creating the test DB solved the problem.

Apologies!
