### ISSUE TITLE
sqlite::memory: is seen as a "remote url"

### ISSUE THREAD

**Issue by jrgns** [DatabaseCleaner/database_cleaner#544]
Some of my projects use `sqlite::memory:` as the URL when doing CI.

The [CI started failing](https://travis-ci.org/EagerELK/ditty/jobs/373193311#L616) though due to the `DatabaseCleaner::Safeguard::Error::RemoteDatabaseUrl` check.

Can `sqlite::memory:` please be seen as a local DB?

**Comment by etagwerker** [comment]
@jrgns Could you test with the latest version in `master`? This should have been fixed by https://github.com/DatabaseCleaner/database_cleaner/pull/529

**Comment by jrgns** [comment]
@etagwerker Sorry, didn't see that issue :)
