### ISSUE TITLE
1.7.0 breaks Cucumber with DATABASE_URL

### ISSUE THREAD

**Issue by DannyBen** [DatabaseCleaner/database_cleaner#554]
After upgrading from 1.6.2 to 1.7.0 I get the friendly (thanks for that) safeguards error when running cucumber features on CI (where it uses DATABASE_URL):
```
ENV['DATABASE_URL'] is set to a remote URL. Please refer to https://github.com/DatabaseCleaner/database_cleaner#safeguards (DatabaseCleaner::Safeguard::Error::RemoteDatabaseUrl)
/gems/gems/database_cleaner-1.7.0/lib/database_cleaner/safeguard.rb:21:in `run'
```

So I went ahead and tried following the instructions in the README section.

First, tried allowing this the Ruby way, inside `features/support/env.rb` (which is the only place I saw `DatabaseCleaner` in my code):

```ruby
begin
  # This is the only line I added, everything else was already here.
  DatabaseCleaner.allow_remote_database_url = ENV['CI']
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end
```

That didn't work, so I tried the environment variable approach, and configured it on Travis:
![image](https://user-images.githubusercontent.com/2405099/40159528-652f0962-59b2-11e8-9dba-6d9164eee520.png)

That didn't work either. Only downgrading to 1.6.2 works.

Am I doing something wrong or is it indeed an issue?

**Comment by dreyks** [comment]
you're probably using DatabaseCleaner call somewhere earlier in the suite. In one of the `before` hooks maybe? look at the complete backtrace

**Comment by DannyBen** [comment]
The only place I am calling `DatabaseCleaner` from my own code is in `features/support/env.rb`

```ruby
DatabaseCleaner.strategy = :transaction
```

**Comment by DannyBen** [comment]
Ok - so I revisited this issue again, and it seems like it was all my fault.

My tests run inside a container, and this container did not have the proper environment variable. Once I fixed it, it is all working as advertised. 

Closing.
