### ISSUE TITLE
Unix sockets should be considered local with Postgres

### ISSUE THREAD

**Issue by fdr** [DatabaseCleaner/database_cleaner#561]
Similar to #528, localish URLs relying on unix sockets are miscategorized with Postgres.

Unix socket urls can look like: `postgres:///dbname` or `postgresql:///dbname` (when using the default unix socket baked into the linked `libpq`) or, more flexibly, `host=/tmp` (`libpq` detects unix sockets with a leading slash: only absolute paths are supported).

I think there is also an IPv6 (`::1`) omission.

**Comment by botandrose** [comment]
Looks like this was addressed by #569. Reopen if not.
