### ISSUE TITLE
Can't `except` tables be partially cleaned?

### ISSUE THREAD

**Issue by gumatias** [DatabaseCleaner/database_cleaner#566]
hi!

This is really a shot in the dark, but I'm hoping someone can provide some guidance :)

I have a table that some of its data is persisted/seeded and others aren't, i.e. they're created in tests. I wanted to clean the latter only, but whichever combination of RSpec lifecycle hooks I try, it doesn't work.

Am I doing something wrong?

```
# database cleaner settings
config.around(:each) do |example|
  # :deletion is necessary for our test suites
  DatabaseCleaner.strategy = :deletion, except: ['user_roles']
  DatabaseCleaner.start
  example.run
  DatabaseCleaner.clean
end

# spec
describe do
  let!(:temporary_user_role) { create :user_roles }

  after do
    temporary_user_role.destroy! # tried `delete` too, no luck.
  end

  it do
    expect(true).to eq(true)
  end
end

```

The new record `temporary_user_role` is still in the table 😞 

Thanks!

**Comment by etagwerker** [comment]
@gumatias Is that all the code related to `database_cleaner`? 

You don't need to define the strategy for each scenario. You can do it before the suite and then `start/clean` around each scenario. See: https://github.com/DatabaseCleaner/database_cleaner#rspec-example

The only reasonable explanation I can think of is that you are somehow within a transaction that hasn't committed, but I don't know if that is the problem. 

Maybe you can try moving this line to a `before(:suite)` block? 

```
DatabaseCleaner.strategy = :deletion, except: ['user_roles']
```

**Comment by gumatias** [comment]
thanks, @etagwerker ! You're right... not related to DB Cleaner at all 🤦‍♀️ 

For whoever else sees this with a similar issue; it had to do with ActAsParanoid!
