### ISSUE TITLE
undefined method `url_whitelist=' for DatabaseCleaner:Module

### ISSUE THREAD

**Issue by jttyeung** [DatabaseCleaner/database_cleaner#572]
```
NoMethodError:
  undefined method `url_whitelist=' for DatabaseCleaner:Module
```

This is occurring because the latest gem version `1.7.0` was released on April 19, 2018 - one day prior to [these changes](https://github.com/DatabaseCleaner/database_cleaner/commit/c0013de1ee7afb4e25a0581940e22408f73273f9) being merged in.

When specifying `gem "database_cleaner", git: "https://github.com/DatabaseCleaner/database_cleaner", ref: "c0013de1ee7afb4e25a0581940e22408f73273f9"`, this fixes the issue mentioned above.

Please re-release the newest gem version so I can remove the gemfile dependency on the commit SHA. 🙏

**Comment by jpwynn** [comment]
It's a little worse that that... if you modify the Gemfile:

`gem 'database_cleaner', :github => 'DatabaseCleaner/database_cleaner', :branch => 'master'`

(and of course run `bundle install`)

running rspec now complains
```
Failure/Error: require "database_cleaner"

LoadError:
  cannot load such file -- database_cleaner
```

even though spec_helper.rb still has `require "database_cleaner"` right where's it's always been.

So the usual advice to use the master branch does not work with the current build state.

**Comment by mickael-palma-argus** [comment]
👍 

Same thing here with `database_cleaner (1.7.0)` and this configuration:
```ruby
require 'database_cleaner'

DatabaseCleaner.url_whitelist = ['postgresql://dbuser:dbpassword@database']

```

**Comment by starduliang** [comment]
Actually I'm using postgres, so url (`postgres://postgres:password@db:5432`) on local is not allowed. I did below trick instead of using `DatabaseCleaner.url_whitelist` to make sure it's still safe on production.
```
require 'database_cleaner'

if Rails.env.test?
  # https://github.com/DatabaseCleaner/database_cleaner#safeguards
  DatabaseCleaner.allow_remote_database_url = true
end
```

**Comment by botandrose** [comment]
Should be resolved now. Closing. Reopen if not!

**Comment by jttyeung** [comment]
Thank you!
