### ISSUE TITLE
Explicit #clean method invocation behavior with parallel_tests

### ISSUE THREAD

**Issue by manuraj17** [DatabaseCleaner/database_cleaner#573]
Hello,

I am trying to understand the implication of having an explicit (although not recommended) call to `DatabaseCleaner.clean` inside an `after` block inside a spec, which is being run in a suite with parallel_tests gem. 

From what I understand the parallel_tests gem runs the specs in different processes each with it's own database. 
Looking at the DatabaseCleaner code I see that the clean method invokes cleaning on all the connections available. 

Since I failed to trace back the code properly, requesting some help in understand what the call to `clean` method will do. Is it going to wipe out the database in the process or leak out to other processes somehow?  I kind of infer that such calls are causing flaky tests but I have not had a solid ground to claim that such method calls cause it.

**Comment by botandrose** [comment]
As long as different databases are indeed set up for each parallel test run, database_cleaner should not cause any issues here. I use it for this myself! Closing this issue, but if you are still experiencing the problem, and can share reproduction steps, please reopen!

**Comment by mario-amazing** [comment]
@botandrose 
```ruby 
  Parallel.map(Array(spreadsheets_data), {in_threads: 1}) do |spreadsheet_data|
      Spreadsheet.first       # NOTE: the spreadsheet is present
      spreadsheet.with_lock do # ERROR spreadsheet is empty(DB cleared), cuz database_cleaner doesn't understand Parallel map, even in 1 thread
          ## Do something
      end
  end
```
Could you help or should I open new issue?
