### ISSUE TITLE
Change date "1.7.0 2017-04-19" in History.rdoc?

### ISSUE THREAD

**Issue by cobot00** [DatabaseCleaner/database_cleaner#583]
Hi, thanks for database cleaner!

`1.7.0 2017-04-19` in History.rdoc, right?
I'm thinking that perhaps `1.7.0 2018-04-19` .

https://github.com/DatabaseCleaner/database_cleaner/commit/ec01c43005cbecbbd785bf6bac118a249329adf9#diff-c65ed44cbe1768797ac07d046c79bdc6

**Comment by etagwerker** [comment]
@cobot00 Good point. That was a typo. Could you submit a PR?

**Comment by cobot00** [comment]
:ok:
