### ISSUE TITLE
[IMPROVEMENT] Switch back README.md on master branch until splitted packages are really available

### ISSUE THREAD

**Issue by hron84** [DatabaseCleaner/database_cleaner#587]
Currently, the default `README.md` states you have to install `database_cleaner-active_record` gem and such stuffs but they are currently not available from https://rubygems.org source, only from your Git. Please update accordingly the README that states it contains informations that aren't valid yet or roll back the default README to relate with currently available packages.

I'm understand you are around to release, but spreading misleading information on the page of the repository confuses users.

**Comment by hron84** [comment]
@borenho the problem is not for me but anyone who tries to use this gem at first time. Your default `README.md` provides not (yet) valid information for newcomers and this can cause mislead and unneccessary issues opening. I think any project should take care about its default `README` to state correct information and release new things only when they land in the code and/or appropriate package repositories. Stating false, fake or misleading information in the description of the repository is a bad message for your uses that you do not take care about documentation enough. 

I just trying to prevent anyone who find the repo first (than a StackOverflow question :D) to rage about required but non-existing packages and spend a few 10 minutes to find out what's happening. I'm understand you as a contributor know everything about the ongoing migration under the hood - an outsider will not if you do not communicate it right.

**Comment by borenho** [comment]
I agree with you @hron84 . I also faced a similar problem and it took me a while to understand. To be truthful, the master docs are a bit misleading. I also commented on it here https://github.com/DatabaseCleaner/database_cleaner-active_record/issues/1.
I too wish the maintainers dedicated the master branch and README to the latest released development version

**Comment by borenho** [comment]
Actually, they'll be releasing v1.8.0 sometime this week, so this will be solved https://github.com/DatabaseCleaner/database_cleaner-active_record/issues/1 🎉

**Comment by gbirchmeier** [comment]
2 months later, still not released.  Readme is still leading people astray..

**Comment by JonRowe** [comment]
The readme explicitly mentions that it is for a unreleased version, and links to the currently released read me, closed by #589

**Comment by hron84** [comment]
@JonRowe Thank you very much!
