### ISSUE TITLE
database_cleaner-active_record  Doesn't exist in https://rubygems.org

### ISSUE THREAD

**Issue by Randall-Coding** [DatabaseCleaner/database_cleaner#596]
The readme indicates to use this gem `gem 'database_cleaner-active_record'`.  Is it going by another name now?

I'm installing this on a Rails 5 app.  Added the required gem to my Gemfile then ran `bundle install`

Output on the console is:
> Fetching gem metadata from https://rubygems.org/...........
> Fetching gem metadata from https://rubygems.org/.
> Could not find gem 'database_cleaner-active_record' in any of the gem sources listed in your Gemfile

*edit adding more details

**Comment by Randall-Coding** [comment]
I'm installing this on a Rails 5 app.  Added the required gem to my Gemfile.  

Output on the console is:
> Fetching gem metadata from https://rubygems.org/...........
> Fetching gem metadata from https://rubygems.org/.
> Could not find gem 'database_cleaner-active_record' in any of the gem sources listed in your Gemfile

.

**Comment by Randall-Coding** [comment]
The only gem on RubyGems is database-cleaner (without the -active_record) and using that seems to work.  I think you just need to update your readme instructions.

**Comment by malkaviano** [comment]
database_cleaner

**Comment by bekicot** [comment]
The readme have a warning that the master branch readme is for unreleased version of the gems.
Use the 1.7.0 readme instead.
https://github.com/DatabaseCleaner/database_cleaner/blob/v1.7.0/README.markdown

It think this issue should be closed.
