### ISSUE TITLE
Truncation except order matters?

### ISSUE THREAD

**Issue by eimermusic** [DatabaseCleaner/database_cleaner#597]
I just setup a new clean Rails app, but against a legacy database where I want to keep some pretty static "seed" data. At least until I move them over as seeds or migrations in Rails.

It seems like
```
    DatabaseCleaner.clean_with(:truncation, {:except => %w[apples, bananas, clementines]})
    DatabaseCleaner.strategy = :truncation, {:except => %w[apples, bananas, clementines]}
```
is not the same as
```
    DatabaseCleaner.clean_with(:truncation, {:except => %w[apples, clementines, bananas]})
    DatabaseCleaner.strategy = :truncation, {:except => %w[apples, clementines, bananas]}
```

The top config works as expected for me whereas the second kept truncating the `apples` and `clementines` but leaving `bananas` alone.

If this seems odd, I would love to get some tips on how to troubleshoot why I get this behavior.

> Note: All table names have been changed to protect the innocent.

**Comment by botandrose** [comment]
@eimermusic My first thought is that this is due to a mistake in your syntax. When you are using the `%w[]` syntax, you must omit the commas, otherwise, they are considered part of the string. For example:

```ruby
%w[a, b, c] == ["a,", "b,", "c"] # => true
%w[a b c] == ["a", "b", "c"] # => true
```

Try removing the commas from your arrays, and then see if your issue is resolved.

**Comment by botandrose** [comment]
Closing, assuming that this resolved your issue.

**Comment by eimermusic** [comment]
Good catch... thanks!
