### ISSUE TITLE
Releases and Maintenance

### ISSUE THREAD

**Issue by botandrose** [DatabaseCleaner/database_cleaner#599]
Hey @etagwerker @JonRowe,

Would you grant me commit and release permissions for the database cleaner family of gems? I'd like to finish the work to get these libraries in good condition, and I know that you two are very busy.

1. Release v1.8.0 and v2.0.0 to get ourselves out of dependency hell
2. Get Appraisal running so we can test multiple versions of Ruby and Rails
3. Merge a bunch of long-standing bugfix PRs that we haven't been able to easily verify without #2 

Relevant qualifications:
1. I'm the #2 contributor  https://github.com/DatabaseCleaner/database_cleaner/graphs/contributors
2. I have 17 PRs merged https://github.com/DatabaseCleaner/database_cleaner/pulls?utf8=%E2%9C%93&q=is%3Amerged+is%3Apr+author%3Abotandrose

What do you think?

**Comment by JonRowe** [comment]
I'm ok with this if @etagwerker is... but I don't feel I have the authority to grant access on my own, although I'm happy to sort out what I can if @etagwerker gives the ok.

**Comment by etagwerker** [comment]
@botandrose I think that is a good idea. Sorry it took so long and welcome to the team of maintainers! 😄 

Just sent you an invitation to the organization.

**Comment by botandrose** [comment]
@etagwerker @JonRowe Hooray! I'm excited to get these improvements out the door. Thanks for your faith in me!

Moving forward, I want to strike the right balance of autonomy to get stuff done without bothering you folks, and collaboration so I don't take the project in an unwanted direction. I was thinking something like the following strategy:

**Semver patch-level changes:** Merge bugfixes and refactorings as I see fit. 
**Semver minor-level changes:** Open a PR for any non-breaking changes to the public API, and merge after a week if there is no discussion or dissent.
**Semver major-level changes:** Open an issue to discuss potential breaking changes to the public API, and proceed with a PR after a week if there is no dissent. Then allow a month for discussion of the PR before merge.

Lastly, how do you want to handle making gem releases on rubygems.org? I don't have permissions for that, yet.

How does all this sound to you fine folks? Questions, comments, clarifications?

**Comment by JonRowe** [comment]
What is your rubygems email, and do you have 2FA turned on? (You should enable it if not).

**Comment by botandrose** [comment]
@JonRowe My rubygems email is micah@botandrose.com, and I have 2FA enabled for that account.

I hear you on the heads-up before releases. What were you thinking? Should I just open a issue beforehand and tag you both?

**Comment by JonRowe** [comment]
I don't mind, a PR is probably the best choice, it just avoids us asking when a release notification comes through, e.g. the shock factor.

**Comment by botandrose** [comment]
Ah, gotcha. That makes sense. Will do!

**Comment by JonRowe** [comment]
I've added you as an owner to the main gem

**Comment by botandrose** [comment]
Thank you, Jon!
