### ISSUE TITLE
Deprecation notice coming from within the lib on windows

### ISSUE THREAD

**Issue by Ex-Ark** [DatabaseCleaner/database_cleaner#632]
### Description of the bug

On windows, the lib fires deprecation notice coming from within it's own code.

```
Calling `DatabaseCleaner[...].create_strategy` is deprecated, and will be removed in database_cleaner 2.0. Use `DatabaseCleaner[...].strategy=` instead.
Calling `DatabaseCleaner[...].set_strategy_db=` is deprecated, and will be removed in database_cleaner 2.0. Use `DatabaseCleaner[...].db=` instead.
Calling `DatabaseCleaner.connections` is deprecated, and will be removed in database_cleaner 2.0. Use `DatabaseCleaner.cleaners`, instead.
```

I suppose this is coming from [called_externally?](https://github.com/DatabaseCleaner/database_cleaner/blob/4dffa84b68bc259b77c57049b32cc26a05b3e07a/lib/database_cleaner/base.rb#L153) checking for `:` in the file path, but on windows you have at least 1 `:` in a file path : `C:`

I quickly debugged it and here's my output :
```ruby
caller.first
# C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/database_cleaner-1.8.3/lib/database_cleaner/base.rb:34:in `strategy=
caller.split(":")
# ["C", "/Ruby25-x64/lib/ruby/gems/2.5.0/gems/database_cleaner-1.8.3/lib/database_cleaner/base.rb", "34", "in `strategy="]
caller.split(":").first
# "C"
__FILE__ != caller.first.split(":").first
# true
```

### Reproduce the bug
- setup a ruby dev env on windows (rvm, mingw, ruby)
- add `gem 'database_cleaner-active_record'` to `Gemfile` && `bundle install`
- add `config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end` to `spec_helper.rb`
- bundle exec rspec

### Expected behaviour

No deprecation notice should come from the lib itself

### ENV
 - ruby 2.5.7p206 (2019-10-01 revision 67816) [x64-mingw32]
 - **database_cleaner (1.8.3)**
 - **database_cleaner-active_record (1.8.0)**

**Comment by botandrose** [comment]
Hello @Ex-Ark,

Wow! This is a really great bug report with excellent detective work! Thank you!

I've just pushed out a bugfix PR: #633, but I don't have access to a Windows box to confirm that it actually fixes the false deprecation warnings. Would you mind trying that branch out and letting me know whether or not it fixes it for you? If it does, I'll merge and release v1.8.4.

**Comment by Ex-Ark** [comment]
Thank you for the quick answer and fix !

Confirmed that using : 
```ruby
gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner', branch: 'fix_windows_deprecation_warnings_false_positive'
```

I have no deprecation notice showing in STDOUT 👍 

Will wait eagerly for 1.8.4 then :)

Keep up the good work

**Comment by botandrose** [comment]
@Ex-Ark Awesome, thanks for testing this for me! And great idea about the unit testing; that's exactly what I did! ;)

https://rubygems.org/gems/database_cleaner/versions/1.8.4
