### ISSUE TITLE
Test coverage tracking?

### ISSUE THREAD

**Issue by botandrose** [DatabaseCleaner/database_cleaner#638]
Hey @etagwerker,

I would like to get some test coverage tracking going, probably either with Coveralls or Code Climate, but there's the question of permissions.

I could set up Coveralls myself, but then I think my @botandrose account would be the only account with permissions, which is not ideal.

Code Climate is already set up, but I don't have the permissions to add test coverage to it.

Do you know of a way to give the DatabaseCleaner organization (and therefore its members) access to one or the other? Or some other solution?

**Comment by etagwerker** [comment]
@botandrose I'm not sure how to add you to Code Climate for you to do this. I think that all you need is the CodeClimate's test reporter ID: 

```
cc9e584acab7d670ac3e645cab4414826deb79e288a23721568b4858f64884d6
```

Do you want to take a stab at it? 

Also, lately I've been using https://codecov.io for new projects. If you're open to adding a new service, we could try with that.

**Comment by botandrose** [comment]
@etagwerker Sure! Whichever you'd prefer is fine with me.

**Comment by botandrose** [comment]
@etagwerker One last thing, I just logged into CodeCov to enable coverage on the adapter repos, and it looks like I have permissions to view the repos under the DatabaseCleaner org, but not add any. Any ideas?

**Comment by etagwerker** [comment]
@botandrose Just added you as an admin in CodeCov. Please test now. 👍
