### ISSUE TITLE
Demote Neo4j adapter?

### ISSUE THREAD

**Issue by botandrose** [DatabaseCleaner/database_cleaner#647]
Howdy, y'all. I'm applying the last bit of polish to the adapters for the v2.0 release, and when I got to the Neo4j adapter, I realized that it needs a lot of work... more than I can give it alone, I think.

First thing I noticed was that the tests are very incomplete, and those that are there aren't actually testing anything about Neo4j at all. They don't even integrate with the database! So I set to trying to make that happen, but I'm running into all sorts of walls with my total lack of knowledge of Neo4j. I can at least tell that the neo4j-core gem needed to be downgraded at least two major versions for this adapter to work, and perhaps the neo4j database, as well.

Looking at the download counts on rubygems.org, this adapter is wayyy down there in downloads, too. https://rubygems.org/search?utf8=%E2%9C%93&query=database_cleaner

Therefore, I'm thinking that we demote this adapter to the discontinued list for v2.0, and if someone who knows Neo4j wants to put in the work to modernize it, they can resurrect it.

Thoughts?

**Comment by etagwerker** [comment]
@botandrose That sounds like a good idea to me. If anyone is passionate about it, they will submit an issue or try to bring it back to life. 

We should signal that `database_cleaner-neo4j` is not actively being maintained and looking for maintainers. Here are a couple ideas. 

- Archive `database_cleaner-neo4j`
- Add an issue to the repo that says we are not actively maintaining it and we are looking for maintainers
- Add a link to this issue from that new issue 

What do you think?

**Comment by etagwerker** [comment]
@botandrose I guess the issue with archiving the repository is that no new comments or issues can be submitted to it. 

I like that an "archived" repository shows a big warning strip on top of the project, but I guess people will have to submit an issue to the core project if they want to restore that adapter.

Are we good with that?

**Comment by botandrose** [comment]
@etagwerker Yeah, I was thinking that, too. I definitely don't want to discourage people from getting involved with the retired adapters. Maybe someone will come by with the intention to do a drive-by PR for one of them, and then end up becoming a maintainer! It happened to me ;)

**Comment by etagwerker** [comment]
Cool! If someone is interested in maintaining database_cleaner-neo4j, hopefully they will find this issue and comment. I'll close this issue for now. 😄
