### ISSUE TITLE
`:connection` vs `#db` confusion. Let's pick one!

### ISSUE THREAD

**Issue by botandrose** [DatabaseCleaner/database_cleaner#649]
@etagwerker These are two ways of saying the same thing, but they look pretty different:

```ruby
DatabaseCleaner[:active_record, connection: :logs]
DatabaseCleaner[:active_record].db = :logs
```

Ignoring, for the moment, that perhaps we could limit this to one (and only one) way, I think we should at least align the naming for v2.0. Options I can think of:

```ruby
DatabaseCleaner[:active_record, db: :logs]
DatabaseCleaner[:active_record].db = :logs
```

```ruby
DatabaseCleaner[:active_record, connection: :logs]
DatabaseCleaner[:active_record].connection = :logs
```

I'm leaning towards `db`, because its shorter, and (at least to me) has a broader connotation, where `connection` makes me think we could only pass a connection object or connection string. This is pretty subjective, for sure, though.

I think whichever one we go with, we could do it in a backwards-compatible way with a deprecation warning.

What do you think?

**Comment by etagwerker** [comment]
@botandrose I think `db` is a little bit more high level and easier to understand. I don't really care about connections when cleaning my database.

**Comment by botandrose** [comment]
@etagwerker Cool, sounds like we're on the same page, then. I'll open a PR for this. Thanks for sharing your input!
