### ISSUE TITLE
Ruby 2.7 deprecations

### ISSUE THREAD

**Issue by ngan** [DatabaseCleaner/database_cleaner#665]
We're using Ruby 2.7 and are getting warnings from this gem:

```
database_cleaner-core-2.0.0.beta2/lib/database_cleaner/cleaners.rb:41: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
database_cleaner-core-2.0.0.beta2/lib/database_cleaner/cleaner.rb:28: warning: The called method `initialize' is defined here
```

I'd be more than happy to put up a PR...is there a minimum version of Ruby that this database_cleaner v2 plans to support?

**Comment by etagwerker** [comment]
@ngan That would be great. We are currently maintaining Ruby 2.5 and higher: https://github.com/DatabaseCleaner/database_cleaner/blob/master/.travis.yml

**Comment by ngan** [comment]
@etagwerker here ya go: https://github.com/DatabaseCleaner/database_cleaner/pull/667
