### ISSUE TITLE
Feature request: specify when to stop re-raising server errors when raise_server_errors=true

### ISSUE THREAD

**Issue by bblack** [DatabaseCleaner/database_cleaner#676]
We use capybara for our feature specs. We have `raise_server_errors` set to `true` (by default).

We also use [database_cleaner](https://github.com/DatabaseCleaner/database_cleaner) to wipe the database after each test, using an RSpec `after` hook. 

Occasionally, we'll have a feature spec example fail, due to this sequence of events:
* the example completes, while there are still requests in progress (typically, XHR for parts of the page that the current example is not concerned with)
* the `after` hooks begin to execute, causing DatabaseCleaner to destroy records as expected
* the server raises an error, because DatabaseCleaner has caused an inconsistent state between the in-progress result and the database. For example:
  * a record's associated record (which is expected to exist because in normal operation the association is enforced) disappears
  * or, one of the DatabaseCleaner queries enters deadlock with a query from an in-progress request.
* capybara catches and re-raises that error

In this case, the error is not of any interest to us. We could set `raise_server_errors = false` to prevent this, but then we'd lose the benefit of the feature entirely.

It would be nice to specify the point at which we no longer care to catch these errors. That would allow us to stop catching the errors after the example finishes, but before our after hook causes DatabaseCleaner to wipe the database.

I'm not familiar with the source here, but it looks like what I'm asking for might be implemented by not calling `raise_server_error!` from `reset!`, while keeping it in other functions like `visit`. Or by being able to put `reset!` in an earlier position than our after hook?

**Comment by botandrose** [comment]
Taking a look at this, this seems to me to be outside the scope of database_cleaner, and should be handled in your test runner somewhere. My initial thought is figure out a way to delay completion of the example until the XHR requests have competed. I remember doing something like this in years past... ah yes, here it is. I will paste below. Note this is from years ago when all my XHR was going through jQuery, but you get the idea. Hope this helps.

Closing this, since I don't think its in scope for this gem, but reopen if you want to try to change my mind :)

```
class AjaxWaiter
  def self.wait!
    new.wait!
  end

  def initialize capybara_session, start_time=Time.now
    self.capybara_session = capybara_session
    self.start_time = start_time
  end

  attr_accessor :capybara_session, :start_time

  def wait!
    loop do
      sleep 0.10
      break if jquery_idle?
      echo "Timed out waiting for ajax to resolve" && break if timed_out?
    end
  end

  private

  def jquery_idle?
    capybara_session.evaluate_script "window.jQuery && (window.sidebarNav ? jQuery.isReady && jQuery.active==0 && window.sidebarNav.isReady : jQuery.isReady && jQuery.active==0)"
  end

  def timed_out?
    (start_time + Capybara.default_max_wait_time) < Time.now
  end
end
```
