### ISSUE TITLE
Deprecation Warning on 2.7

### ISSUE THREAD

**Issue by maxwell** [DatabaseCleaner/database_cleaner#678]
```
/Users/maxwell/.rbenv/versions/2.7.1/lib/ruby/2.7.0/forwardable.rb:235: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/maxwell/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:11: warning: The called method `[]' is defined here
```

Worth noting, we perhaps are doing some non-standard access to handle having multiple databases.

```ruby

    DatabaseCleaner[:active_record, { db: Extracts::Version }].clean_with :truncation
    DatabaseCleaner[:active_record, { db: Extracts::ApplicationRecord }].clean_with :truncation

    DatabaseCleaner[:active_record, { db: ApplicationRecord }].clean_with :truncation
```

**Comment by swiknaba** [comment]
seems like the same issues described here: https://github.com/DatabaseCleaner/database_cleaner/issues/677

**Comment by botandrose** [comment]
@maxwell @swiknaba I'm unable to reproduce this warning on 2.7.2, or as an error in 3.0.0. Can you help me with instructions, or better yet, add a test to expose this?

**Comment by etagwerker** [comment]
@maxwell I can't reproduce this with 2.7.2 either. Please reopen if you can provide more details. Thanks!

**Comment by swiknaba** [comment]
2.7.2 turned off these warnings: https://bugs.ruby-lang.org/issues/17000 so this has to be tested on 2.7.1 and 3.
Did you test if it actually works on 3.0 @etagwerker?
