### ISSUE TITLE
Poor strategy class lookup

### ISSUE THREAD

**Issue by softpro** [DatabaseCleaner/database_cleaner#680]
You should use `strategy.to_s.classify` instead of `strategy.to_s.capitalize` in `DatabaseCleaner::Cleaner#orm_strategy`.
https://github.com/DatabaseCleaner/database_cleaner/blob/a34c4c3d94d7397878e3510987093f17603f81cf/lib/database_cleaner/cleaner.rb#L89

**Comment by botandrose** [comment]
You're absolutely right! Wanna make a PR?
