### ISSUE TITLE
API documentation is empty

### ISSUE THREAD

**Issue by arowla** [DatabaseCleaner/database_cleaner#688]
The link to docs on [the homepage](http://databasecleaner.github.io/) goes to an empty page:

https://www.rubydoc.info/gems/database_cleaner

![Screen Shot 2021-11-10 at 4 26 55 PM](https://user-images.githubusercontent.com/166715/141203913-0d337697-8443-4cce-9c96-1429e8c63689.png)

**Comment by etagwerker** [comment]
@arowla Thanks for submitting this issue! 

I went ahead and updated our [README](https://github.com/DatabaseCleaner/database_cleaner#changelog) and repo settings: https://github.com/DatabaseCleaner/database_cleaner -- We haven't been using https://databasecleaner.github.io for release documentation for a while.

I also added a note to https://databasecleaner.github.io to explain that that page is deprecated. 👍
