### ISSUE TITLE
Prevent cleaning of development database

### ISSUE THREAD

**Issue by cherbst-2112** [DatabaseCleaner/database_cleaner#704]
Opened this PR a few weeks ago to generalize ProductionEnv safeguard to prevent clearing of a development database:

https://github.com/DatabaseCleaner/database_cleaner/pull/703

Did not see any comments on the PR so thought I'd open an issue to get some visibility. Thanks!

**Comment by etagwerker** [comment]
@cherbst-2112 Thanks for the ping! I just commented on #703
