### ISSUE TITLE
Deprecation warning on: DatabaseCleaner.clean_with(:truncation)

### ISSUE THREAD

**Issue by abacha** [DatabaseCleaner/database_cleaner#708]
I'm using **database_cleaner-active_record (2.1.0)** and everytime that I trigger .clean_with(:truncation) it warns me a deprecation msg:
`DEPRECATION WARNING: #tables currently returns both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only return tables. Use #data_sources instead.`

is it possible to fix this?

**Comment by etagwerker** [comment]
This is odd because this has been fixed for many years. https://github.com/DatabaseCleaner/database_cleaner-active_record/commit/44a173124aa1da09467e2075f051b470ae1080d7 

Please double check your database_cleaner version.
