### ISSUE TITLE
New Strategy: The Snapshot

### ISSUE THREAD

**Issue by joevandyk** [DatabaseCleaner/database_cleaner#80]
I'd like to be able to use transactions inside my tests, so that rules out the transaction strategy.  

My general pattern when running tests:
1. Remove all the data from the database
2. Load some initial data using factories
3. Run tests, reverting back to the initial data after each test run

I would use the deletion or truncate pattern (fwiw, deletion is much faster than truncate for me with postgresql), but they don't revert the data to the initial state -- they erase everything.  Which means I need to re-run the factories each time, which is really slow.

How the snapshot pattern should work:
1.  Remove all the data from the database
2.  Load some initial data using factories
3.  Save a dump of the database to a temp file (probably just the data, not the schema)
4.  After each test run:
   - Remove all the data from the database using the deletion strategy
   - Using raw sql, load the data dump back into the database

This would let me use transactions in tests and quickly revert to a good initial state.  It probably wouldn't be as fast as the transaction pattern, but I think that would be impossible to achieve, until postgresql lets us roll back to an earlier transaction.

**Comment by Overbryd** [comment]
Here is my setup, that I found to be very fast and handy on my PostgreSQL projects. Maybe it helps for considering such a feature.

1. Generate data (in my case I run my development seed that also creates a dump)
2. Use `pg_dump` with the following additional options:
    * `--clean` to ensure clean state
    * `--compress=9` smaller in size, less stuff to move around
    * `--format=c` custom format, faster when restoring
3. Use `pg_restore` on the dump:
    * `--jobs 4` parallel restore
    * `--clean` to ensure clean state

I would love to see something like this in a `DatabaseCleaner.snapshot` strategy.

For these tests I use the `:deletion` strategy to clean up afterwards.
Runs super fast, even on bigger datasets. My db/seed.rb uses my normal factories to generate the data.
