### ISSUE TITLE
strange issue with changing strategies and AR `after_commit` hooks

### ISSUE THREAD

**Issue by agibralter** [DatabaseCleaner/database_cleaner#99]
Wow this was a hard thing to track down. It turns out that if ActiveRecord models with after_commit hooks get created in a transactional (`DatabaseCleaner.strategy = :transaction`) example and then a non-transactional example runs, all the left over objects' after_commit hooks will fire on the first "COMMIT" of the non-transactional example. This is because DatabaseCleaner does not call `rollback_transaction_records`...

I had to manually add this as an `after` hook in RSpec:

`ActiveRecord::Base.connection.send(:rollback_transaction_records, true)`

Perhaps something like this could go around here in the code?

https://github.com/bmabey/database_cleaner/blob/master/lib/database_cleaner/active_record/transaction.rb#L19

**Comment by nitzanav** [comment]
Hi,

I am using this configuration:
`
config.use_transactional_examples = false
    config.before(:suite) do
      DatabaseCleaner.strategy = :transaction
      DatabaseCleaner.clean_with(:transaction)
    end
    config.before(:suite) do
      DatabaseCleaner.start
    end
    config.after(:suite) do
      DatabaseCleaner.clean
    end
`

and [test_after_commit](https://github.com/grosser/test_after_commit) gem fixed the issue.
Is it the intended solution?
